import json, sqlite3, re, os
from datetime import datetime, timezone

DB_PATH = '/home/z/my-project/db/custom.db'

with open('/tmp/fc_images.json') as f:
    fc_images = json.load(f)

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

def slugify(text):
    text = text.lower()
    text = re.sub(r'[^\w\s-]', '', text)
    return '-'.join(w for w in text.split() if w).strip('-')[:80]

def get_img(idx):
    return fc_images[idx % len(fc_images)] if fc_images else ''

now = datetime.now(timezone.utc).isoformat()

formations = []

# ANIMATEUR / OPERATEUR
formations.append({"title":"Travail en Hauteur - Operateur","slug":"travail-en-hauteur-operateur","shortDescription":"Formation reglementaire pour les travailleurs intervenant en hauteur. Utilisation des EPI antichute, harnais, longes et lignes de vie selon la norme NM EN 363.","fullDescription":"Cette formation permet aux operateurs d'acquerir les competences necessaires pour travailler en securite en hauteur, conformement a la reglementation marocaine et aux normes internationales. Elle couvre l'identification des risques, l'utilisation correcte des EPI antichute (harnais, longes, absorbeurs de choc, lignes de vie), les techniques de deplacement sur des structures, et les procedures de secours en cas de chute.","level":"Animateur","duration":"2 jours (14h)","prerequisites":"Aucun prerequis","objectives":json.dumps(["Identifier les risques lies au travail en hauteur","Choisir et verifier les EPI antichute adaptes","Maitriser les techniques d'ancrage et de deplacement","Appliquer les procedures de secours en cas de chute","Connaitre la reglementation applicable"]),"program":json.dumps(["Cadre reglementaire (Code du travail, normes NM EN)","Risques specifiques du travail en hauteur","EPI antichute : types, verification, mise en oeuvre","Techniques d'ancrage et de raccordement","Deplacement sur structures : toiture, echafaudage, pylone","Procedures de secours et de sauvetage","Exercices pratiques sur plateforme"]),"price":"2 500 DH / participant","mode":"presentiel","featured":True,"order":0})

formations.append({"title":"Espace Confini - Operateur","slug":"espace-confini-operateur","shortDescription":"Permis d'entree en espace confini. Identification des gaz dangereux, utilisation des detecteurs, procedures d'entree/sortie et plan de sauvetage.","fullDescription":"Formation indispensable pour tout personnel devant penetrer dans des espaces confines (cuves, reservoirs, fosses, reseaux). Les participants apprennent a identifier les dangers specifiques (atmosphere toxique, manque d'oxygene, risques mecaniques), a utiliser les equipements de detection de gaz, a mettre en oeuvre les procedures de ventilation et a appliquer les protocoles de sauvetage.","level":"Animateur","duration":"2 jours (14h)","prerequisites":"Aucun prerequis","objectives":json.dumps(["Reconnaitre un espace confini et ses dangers","Utiliser un detecteur multigaz","Mettre en oeuvre la ventilation et le balisage","Appliquer les procedures d'entree et de sortie","Connaitre le plan de sauvetage"]),"program":json.dumps(["Definition et identification des espaces confines","Risques : atmospheriques, mecaniques, chimiques, thermiques","Equipements de detection de gaz","Ventilation et assainissement de l'atmosphere","Equipements de protection : harnais, trepied, treuil","Procedures de travail et d'autorisation","Plan de sauvetage et exercices pratiques"]),"price":"2 800 DH / participant","mode":"presentiel","featured":True,"order":1})

formations.append({"title":"Habilitation Electrique B0/B0V","slug":"habilitation-electrique-b0-b0v","shortDescription":"Formation reglementaire pour le personnel effectuant des travaux d'ordre non electrique a proximite d'installations electriques. Norme NM/FC 18-550.","fullDescription":"Cette formation delivre l'habilitation electrique B0 ou B0V, obligatoire pour tout travailleur effectuant des operations d'ordre non electrique (peinture, maconnerie, nettoyage) a proximite d'installations electriques sous tension. Elle couvre les risques electriques, la distance minimale d'approche, les consignes de securite et la conduite a tenir en cas d'accident electrique.","level":"Animateur","duration":"1 jour (7h)","prerequisites":"Aucun prerequis","objectives":json.dumps(["Comprendre les risques electriques fondamentaux","Appliquer les distances minimales d'approche","Mettre en oeuvre les consignes de securite","Connaitre la conduite a tenir en cas d'accident","Obtenir l'attestation d'habilitation B0/B0V"]),"program":json.dumps(["Effets du courant sur le corps humain","Parametres electriques : tension, courant, resistance","Zones de voisinage et distances d'approche","Travaux non electriques en zone electrique","Consignes de securite et signalisation","Conduite a tenir en cas d'electrisation","Examen theorique et pratique"]),"price":"1 800 DH / participant","mode":"presentiel","featured":True,"order":2})

formations.append({"title":"Sauveteur Secouriste du Travail (SST)","slug":"sauveteur-secouriste-travail","shortDescription":"Formation obligatoire pour les secouristes en entreprise. Gestes de premiers secours, PSC1, utilisation du DAE et protocoles d'urgence.","fullDescription":"La formation de Sauveteur Secouriste du Travail (SST) permet d'acquerir les competences necessaires pour porter secours a une victime en attendant l'arrivee des secours professionnels. Programme conforme aux recommandations de l'INRS, incluant la protection, l'alerte, la prise en charge des blessures, malaises, hemorragies, brulures et l'utilisation du defibrillateur automatise externe (DAE).","level":"Animateur","duration":"3 jours (21h)","prerequisites":"Aucun prerequis","objectives":json.dumps(["Proteger et alerter en cas d'accident","Examiner la victime et faire le bilan","Pratiquer les gestes de premiers secours","Utiliser un DAE en securite","Transmettre le bilan au service de secours"]),"program":json.dumps(["Proteger / Alerter / Secourir (PAS)","La chaine des secours en entreprise","Examen de la victime (bilan)","Hemorragies : compression, point de compression","Malaise et obstruction des voies aeriennes","Brulures : evaluation et premiers gestes","Plaies et traumatismes","Utilisation du DAE","Exercices de simulation d'accidents"]),"price":"3 200 DH / participant","mode":"presentiel","featured":False,"order":3})

formations.append({"title":"Manutention Manuelle et Gestes et Postures","slug":"manutention-manuelle-gestes-postures","shortDescription":"Prevention des troubles musculosquelettiques (TMS). Techniques de port de charge, gestes de deplacement et ergonomie au poste de travail.","fullDescription":"Formation pratique pour prevenir les risques lies a la manutention manuelle, premiere cause de maladies professionnelles. Les participants apprennent les principes de base du port de charge, les techniques de levage et de deplacement, l'utilisation des aides mecaniques et les principes ergonomiques pour l'amenagement du poste de travail.","level":"Animateur","duration":"1 jour (7h)","prerequisites":"Aucun prerequis","objectives":json.dumps(["Connaitre les limites reglementaires du port de charge","Appliquer les bonnes techniques de levage","Evaluer les risques du poste de travail","Utiliser les aides a la manutention","Adapter son poste de travail (ergonomie)"]),"program":json.dumps(["Reglementation et statistiques des TMS","Anatomie et mecanique du dos","Principes de base du port de charge","Techniques de levage a 1 et 2 operateurs","Aides mecaniques : diable, transpalette, pont roulant","Evaluation du risque par le principe du GIFACT","Exercices pratiques de manutention"]),"price":"1 500 DH / participant","mode":"presentiel","featured":False,"order":4})

# SUPERVISEUR / CHEF D'EQUIPE
formations.append({"title":"Travail en Hauteur - Superviseur","slug":"travail-en-hauteur-superviseur","shortDescription":"Formation avancee pour les superviseurs encadrant des travaux en hauteur. Gestion des permis de travail, verification des EPI et supervision des equipes.","fullDescription":"Formation destinee aux chefs d'equipe et superviseurs devant encadrer des travaux en hauteur. Elle couvre la gestion des permis de travail, l'evaluation prealable des risques, la verification des equipements de protection, la planification des interventions et les procedures de coordination entre entreprises intervenantes.","level":"Superviseur","duration":"3 jours (21h)","prerequisites":"Formation operateur travail en hauteur recommandee","objectives":json.dumps(["Planifier et organiser des travaux en hauteur","Evaluer les risques et rediger un permis de travail","Verifier les EPI et les equipements de protection","Superviser les interventions en securite","Gerer la coordination multi-entreprises","Conduire une enquete d'accident de travail"]),"program":json.dumps(["Rappel des risques et reglementation","Gestion des permis de travail (Permit to Work)","Evaluation prealable des risques (methode HIRA)","Verification et maintenance des EPI antichute","Techniques de supervision et de communication","Coordination SPS sur les chantiers","Gestion des situations d'urgence en hauteur","Etude de cas et exercices de simulation"]),"price":"4 500 DH / participant","mode":"presentiel","featured":True,"order":5})

formations.append({"title":"Espace Confini - Superviseur","slug":"espace-confini-superviseur","shortDescription":"Formation pour les superviseurs responsables des operations en espace confini. Gestion des autorisations d'entree, surveillance continue et plan de secours.","fullDescription":"Formation avancee pour les superviseurs et surveillants charges d'autoriser et de superviser les entrees en espaces confines. Elle couvre l'evaluation des risques, la gestion des permis d'entree, la mise en place du triptyque surveillance-communication-secours, et les obligations legales du surveillant.","level":"Superviseur","duration":"3 jours (21h)","prerequisites":"Formation operateur espace confini recommandee","objectives":json.dumps(["Evaluer les risques specifiques a chaque espace confini","Rediger et gerer les autorisations d'entree","Organiser la surveillance continue des interventions","Mettre en oeuvre le plan de sauvetage","Coordonner les secours avec les services d'urgence"]),"program":json.dumps(["Reglementation et responsabilites du surveillant","Evaluation des risques : gaz, manque O2, mecaniques","Procedure d'autorisation d'entree","Surveillance continue : communication, monitoring","Plan de sauvetage : moyens, equipements, exercices","Retour d'experience et gestion des incidents","Exercice de simulation complet"]),"price":"4 800 DH / participant","mode":"presentiel","featured":True,"order":6})

formations.append({"title":"Habilitation Electrique BR/BC","slug":"habilitation-electrique-br-bc","shortDescription":"Formation pour les charges de travaux et charges d'intervention electrique. Execution et supervision des interventions BT et TBT selon NM/FC 18-550.","fullDescription":"Formation pour l'obtention de l'habilitation BR (charge de travaux electriques) et BC (charge d'interventions elementaires). Elle permet de superviser et d'executer des travaux d'ordre electrique en basse tension (BT) et tres basse tension (TBT), en appliquant les procedures de consignation, de verification d'absence de tension et de remise sous tension.","level":"Superviseur","duration":"3 jours (21h)","prerequisites":"Habilitation B0 ou equivalent, experience en electricite","objectives":json.dumps(["Executer et superviser des travaux electriques BT/TBT","Appliquer les procedures de consignation","Verifier l'absence de tension (VAT)","Rediger les avis de consignation","Obtenir l'habilitation BR ou BC"]),"program":json.dumps(["Rappels d'electricite et risques electriques","Consignation : separation, condamnation, identification, VAT","Redaction de l'avis de consignation","Travaux hors tension : procedures et verifications","Travaux au voisinage : distances et protections","Interventions elementaires BC : remplacement, raccordement","Examen theorique et pratique"]),"price":"5 000 DH / participant","mode":"presentiel","featured":True,"order":7})

formations.append({"title":"CACES R489 - Conduite de Chariots Automoteurs","slug":"caces-r489-chariots-automoteurs","shortDescription":"Certificat d'aptitude a la conduite en securite (CACES) pour chariots automoteurs de manutention. Categories 1A, 1B, 3, 5 selon le type d'engin.","fullDescription":"Formation certifiante pour l'obtention du CACES R489, obligatoire pour la conduite de chariots automoteurs en entreprise. Le programme couvre la conduite de chariots elevateurs en porte-a-faux (cat. 1A/1B), a mat retractable (cat. 3) et a chargement lateral (cat. 5), avec une partie theorique et une pratique intensive sur plateau.","level":"Superviseur","duration":"3 a 5 jours selon categorie","prerequisites":"Permis de conduire B, age minimum 18 ans","objectives":json.dumps(["Conduire un chariot en securite","Effectuer les verifications avant utilisation","Manutentionner et stocker des charges","Connaitre la reglementation et les responsabilites","Obtenir le CACES R489"]),"program":json.dumps(["Reglementation et responsabilites du conducteur","Types de chariots et caracteristiques techniques","Verifications avant et apres utilisation","Conduite : demarrage, marche, direction, levage","Manutention de charges : prise, transport, depose","Circulation en securite et regles de priorite","Exercices pratiques sur plateau","Examen theorique et pratique CACES"]),"price":"5 500 DH / participant","mode":"presentiel","featured":False,"order":8})

# RESPONSABLE QHSE
formations.append({"title":"Analyse des Risques Professionnels (HIRA)","slug":"analyse-risques-hira","shortDescription":"Methodologie complete d'identification et d'evaluation des risques professionnels. HIRA, matrice des risques et plan d'action prevention.","fullDescription":"Formation destinee aux responsables QHSE et chefs de service pour maitriser les methodologies d'analyse des risques professionnels. Le programme couvre l'identification systematique des dangers, l'evaluation de la probabilite et de la gravite, la hierarchisation des risques et l'elaboration de plans d'action de prevention conformes au Code du travail marocain.","level":"Responsable","duration":"3 jours (21h)","prerequisites":"Connaissances de base en QHSE","objectives":json.dumps(["Maitriser la methodologie HIRA","Evaluer les risques selon la matrice probabilite-gravite","Hierarchiser les risques et definir les mesures de controle","Elaborer un plan d'action de prevention","Mettre en place le Document Unique de securite"]),"program":json.dumps(["Cadre reglementaire marocain et international","Methodologie HIRA en 5 etapes","Identification des dangers par famille","Evaluation de la probabilite et de la gravite","Matrice des risques et criticite","Mesures de prevention : elimination, substitution, EPC, EPI","Documentation et suivi des plans d'action","Etude de cas sectoriels et ateliers pratiques"]),"price":"6 000 DH / participant","mode":"hybride","featured":True,"order":9})

formations.append({"title":"Gestion des Permis de Travail","slug":"gestion-permis-travail","shortDescription":"Maitrise du systeme des permis de travail pour les operations a haut risque : feu, hauteur, espace confini, excavation, travaux chauds.","fullDescription":"Formation complete sur la gestion des permis de travail (Permit to Work), outil essentiel de la maitrise des risques pour les operations dangereuses. Le programme couvre les differents types de permis, la procedure de delivrance, les controles a effectuer, la cloture du permis et le suivi documentaire.","level":"Responsable","duration":"2 jours (14h)","prerequisites":"Connaissances de base en QHSE","objectives":json.dumps(["Comprendre les principes du systeme des permis de travail","Rediger et gerer les differents types de permis","Effectuer les verifications de securite requises","Gerer la cloture et le suivi documentaire","Integrer les permis dans le systeme de management QHSE"]),"program":json.dumps(["Principes et objectifs du systeme des permis de travail","Types de permis : feu, hauteur, espace confini, excavation, travaux chauds","Procedure de delivrance : demande, verification, approbation","Controles de securite prealables a l'execution","Gestion des situations d'urgence pendant les travaux","Cloture du permis et retour d'experience","Systeme documentaire et archivage","Ateliers de redaction de permis"]),"price":"4 500 DH / participant","mode":"presentiel","featured":False,"order":10})

formations.append({"title":"Audit QHSE et Evaluation de Conformite","slug":"audit-qhse-conformite","shortDescription":"Formation a la conduite d'audits QHSE selon la norme ISO 19011. Planification, realisation, redaction du rapport et suivi des actions correctives.","fullDescription":"Formation intensive pour acquerir les competences d'auditeur QHSE. Le programme suit la methodologie de la norme ISO 19011:2018 et couvre la planification de l'audit, la preparation des check-lists, la realisation des entretiens et observations, l'evaluation des conformites, la redaction du rapport et le suivi des actions correctives.","level":"Responsable","duration":"4 jours (28h)","prerequisites":"Connaissance des normes ISO 9001/14001/45001","objectives":json.dumps(["Planifier un programme d'audit QHSE","Preparer et realiser un audit selon l'ISO 19011","Rediger des constats et des rapports d'audit","Suivre les actions correctives et evaluer leur efficacite","Developper un esprit critique et d'independance"]),"program":json.dumps(["Principes de l'audit selon l'ISO 19011","Types d'audits et role de l'auditeur","Programmation et planification des audits","Preparation : check-lists, revue documentaire","Techniques d'entretien et d'observation","Evaluation des conformites et classification des non-conformites","Redaction du rapport d'audit","Suivi et verification des actions correctives","Exercice d'audit simule"]),"price":"7 500 DH / participant","mode":"hybride","featured":True,"order":11})

formations.append({"title":"Incendie - Equipier de Premiere Intervention","slug":"incendie-equipier-premiere-intervention","shortDescription":"Formation a la lutte contre l'incendie au niveau de la premiere intervention. Utilisation des extincteurs, evacuation et mise en securite des personnes.","fullDescription":"Formation conforme a la reglementation pour former les equipiers de premiere intervention (EPI) et les chefs d'equipe d'evacuation. Les participants apprennent a utiliser les moyens de premiere intervention (extincteurs, robinets d'incendie), a organiser l'evacuation du personnel, et a cooperer avec les services de secours.","level":"Responsable","duration":"2 jours (14h)","prerequisites":"Aucun prerequis","objectives":json.dumps(["Comprendre le triangle du feu et les classes de feux","Utiliser les extincteurs appropries","Organiser l'evacuation du personnel","Mettre en oeuvre le plan d'evacuation","Cooperer avec les services de secours"]),"program":json.dumps(["Le triangle du feu et la combustion","Classes de feux et extincteurs adaptes","Moyens de premiere et deuxieme intervention","Utilisation pratique des extincteurs sur feu reel","Plan d'evacuation et exercice d'evacuation","Organisation de la lutte contre l'incendie","Systemes de detection et d'alarme incendie","Exercice d'evacuation et de mise en securite"]),"price":"3 500 DH / participant","mode":"presentiel","featured":False,"order":12})

# MANAGER / DIRECTEUR
formations.append({"title":"Management QHSE et Leadership Securite","slug":"management-qhse-leadership-securite","shortDescription":"Developper une culture securite forte au niveau managerial. Engagement de la direction, indicateurs de performance et communication QHSE.","fullDescription":"Formation strategique pour les directeurs et managers souhaitant developper une culture securite exemplaire dans leur organisation. Le programme couvre l'engagement de la direction, la construction d'une culture de securite proactive, le pilotage par les indicateurs, la communication QHSE et la gestion des parties interessees.","level":"Manager","duration":"3 jours (21h)","prerequisites":"Experience en management","objectives":json.dumps(["Developper un leadership engage en matiere de securite","Construire une culture de securite proactive","Piloter la performance QHSE par les indicateurs","Communiquer efficacement sur les enjeux QHSE","Integrer le QHSE dans la strategie de l'entreprise"]),"program":json.dumps(["Le role du manager dans la culture securite","Les 4 niveaux de culture securite (Parker et al.)","Indicateurs de resultat et indicateurs de pilotage","Tableau de bord QHSE et reporting","Communication interne et externe QHSE","Gestion des parties interessees","Revue de direction et amelioration continue","Etudes de cas : succes et echecs de la culture securite"]),"price":"8 500 DH / participant","mode":"hybride","featured":True,"order":13})

formations.append({"title":"Systeme de Management Integre QSE (SMI)","slug":"systeme-management-integre-qse","shortDescription":"Mise en oeuvre d'un SMI combinant ISO 9001, ISO 14001 et ISO 45001. Approche integree, cartographie des processus et audit multi-referentiel.","fullDescription":"Formation pour les responsables QHSE et directeurs qualite/securite/environnement souhaitant mettre en place ou ameliorer un Systeme de Management Integre (SMI). Le programme aborde l'approche integree des 3 normes a travers la Structure de Haut Niveau (SHS), la cartographie transversale des processus, la documentation integree et la certification multi-referentielle.","level":"Manager","duration":"5 jours (35h)","prerequisites":"Connaissance des normes ISO 9001/14001/45001","objectives":json.dumps(["Comprendre la Structure de Haut Niveau (SHS)","Cartographier les processus transversaux QSE","Elaborer une documentation integree","Planifier des audits multi-referentiels","Preparer la certification QSE integree"]),"program":json.dumps(["La Structure de Haut Niveau (SHS) des normes ISO","Contexte et parties interessees integres","Approche risques et opportunites QSE","Cartographie des processus transversaux","Documentation integree : politique, manuel, procedures","Objectifs et indicateurs QSE integres","Audit integre selon l'ISO 19011","Preparation a la certification multi-referentielle","Plan d'action et feuille de route"]),"price":"12 000 DH / participant","mode":"hybride","featured":True,"order":14})

formations.append({"title":"Veille Reglementaire et Conformite QHSE","slug":"veille-reglementaire-conformite-qhse","shortDescription":"Methodologie et outils pour la veille reglementaire QHSE. Registre reglementaire, matrice de conformite et gestion des echeances.","fullDescription":"Formation pour les responsables QHSE et juristes d'entreprise sur la mise en place d'un systeme de veille reglementaire structure. Le programme couvre l'identification des textes applicables, la surveillance des evolutions legislatives, l'analyse d'impact, la gestion de la conformite et les outils de veille disponibles.","level":"Manager","duration":"2 jours (14h)","prerequisites":"Connaissances de base en QHSE et reglementation","objectives":json.dumps(["Mettre en place un systeme de veille reglementaire","Constituer et maintenir un registre reglementaire","Evaluer et suivre la conformite reglementaire","Anticiper les evolutions legislatives","Utiliser les outils de veille professionnels"]),"program":json.dumps(["Cadre reglementaire QHSE au Maroc et a l'international","Sources reglementaires : BO, sites ministeriels, OIT, ISO","Methodologie de veille : identification, collecte, analyse, diffusion","Registre reglementaire et matrice de conformite","Outils de veille : logiciels, alertes, calendriers","Gestion des mises en conformite et planification","Responsabilite et sanctions en cas de non-conformite","Atelier : constitution d'un registre reglementaire"]),"price":"5 500 DH / participant","mode":"hybride","featured":False,"order":15})

formations.append({"title":"Investigation d'Accidents et Analyse des Causes Racines","slug":"investigation-accidents-causes-racines","shortDescription":"Methodologie d'investigation des accidents du travail. Arbre des causes, diagramme d'Ishikawa, methode des 5 Pourquoi et retour d'experience.","fullDescription":"Formation pour les responsables QHSE, chefs de service et membres de CSHT sur les techniques d'investigation des accidents du travail. Le programme couvre les obligations legales d'enquete, la preservation des indices, les methodes d'analyse des causes (5 Pourquoi, Ishikawa, arbre des causes), la redaction du rapport d'enquete et la capitalisation du retour d'experience.","level":"Manager","duration":"3 jours (21h)","prerequisites":"Connaissances de base en QHSE","objectives":json.dumps(["Conduire une enquete d'accident selon la methodologie","Appliquer les outils d'analyse des causes racines","Rediger un rapport d'enquete professionnel","Capitaliser sur le retour d'experience (REX)","Definir des actions correctives efficaces"]),"program":json.dumps(["Obligations legales d'enquete (Code du travail)","Preservation de la scene d'accident et collecte d'indices","Methode des 5 Pourquoi","Diagramme d'Ishikawa (5M)","Arbre des causes (AND/OR)","Methode DMAC","Redaction du rapport d'enquete","Retour d'experience et capitalisation","Etude de cas reels et exercices pratiques"]),"price":"6 500 DH / participant","mode":"hybride","featured":False,"order":16})

created = 0
skipped = 0

for i, f in enumerate(formations):
    cursor.execute("SELECT id FROM Formation WHERE slug = ?", (f['slug'],))
    if cursor.fetchone():
        skipped += 1
        continue
    
    cover = get_img(i)
    
    try:
        cursor.execute("""
            INSERT INTO Formation (id, title, slug, shortDescription, fullDescription, level, duration,
                prerequisites, objectives, program, price, mode, coverImage, featured, "order", createdAt, updatedAt)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            f"fc_{f['slug'][:35]}_{i}", f['title'], f['slug'], f['shortDescription'], f['fullDescription'],
            f['level'], f['duration'], f['prerequisites'], f['objectives'], f['program'],
            f['price'], f['mode'], cover, f['featured'], f['order'], now, now
        ))
        created += 1
        print(f"OK [{f['level']}] {f['title']}")
    except Exception as e:
        if 'UNIQUE' in str(e):
            skipped += 1
        else:
            print(f"ERR: {f['title']} - {e}")

conn.commit()

print(f"\n{'='*60}")
print(f"Creees: {created}, Ignored: {skipped}")

cursor.execute("""SELECT level, COUNT(*) FROM Formation GROUP BY level ORDER BY 
    CASE level WHEN 'Animateur' THEN 1 WHEN 'Superviseur' THEN 2 WHEN 'Responsable' THEN 3 WHEN 'Manager' THEN 4 END""")
print("\nPar niveau:")
for row in cursor.fetchall():
    print(f"  {row[0]}: {row[1]} formations")

cursor.execute("SELECT COUNT(*) FROM Formation")
print(f"\n  TOTAL: {cursor.fetchone()[0]} formations")

conn.close()