import json, sqlite3, os, time
from datetime import datetime

DB_PATH = '/home/z/my-project/db/custom.db'

with open('/tmp/all_images.json') as f:
    images = json.load(f)

def img(cat, idx):
    arr = images.get(cat, [])
    return arr[idx % len(arr)] if arr else ''

def slugify(text):
    import unicodedata
    text = text.lower()
    text = unicodedata.normalize('NFD', text).encode('ascii', 'ignore').decode('ascii')
    return '-'.join(w for w in text.split() if w).strip('-')

def get_cat_id(cursor, slug):
    cursor.execute("SELECT id FROM Category WHERE slug = ?", (slug,))
    row = cursor.fetchone()
    return row[0] if row else None

articles = [
  # ══════════ QUALITE (10) ══════════
  {"cat":"qualite","title":"ISO 9001:2015 — Guide complet de la norme qualité","excerpt":"La norme ISO 9001:2015 est la référence mondiale en matière de management de la qualité. Découvrez ses exigences, sa structure et les bénéfices pour votre organisation.","content":"# ISO 9001:2015 — Guide complet de la norme qualité\n\n## Introduction\n\nLa norme **ISO 9001:2015** est le standard international le plus reconnu en matière de systèmes de management de la qualité (SMQ). Publiée par l'Organisation internationale de normalisation (ISO), elle fournit un cadre structuré pour aider les organisations à garantir la qualité de leurs produits et services.\n\n## Structure de la norme (High-Level Structure)\n\nL'ISO 9001:2015 adopte la **Structure de Haut Niveau (SHS)** commune à toutes les normes de systèmes de management, avec 7 clauses principales :\n\n1. **Contexte de l'organisation** — Comprendre les besoins et attentes des parties intéressées\n2. **Leadership** — L'engagement de la direction et la politique qualité\n3. **Planification** — Les objectifs qualité et la planification des changements\n4. **Support** — Les ressources, les compétences, la communication et l'information documentée\n5. **Réalisation des activités opérationnelles** — La maîtrise des processus et la production\n6. **Évaluation des performances** — La surveillance, la mesure, l'analyse et l'audit interne\n7. **Amélioration** — Les non-conformités, l'audit et l'amélioration continue\n\n## Principales exigences\n\n### Approche processus (§4.4)\nL'organisation doit déterminer les processus nécessaires au SMQ, leur séquence et leurs interactions. Cette approche permet une meilleure compréhension et maîtrise du système.\n\n### Leadership et engagement (§5.1)\nLa direction doit démontrer son leadership et son engagement en établissant une politique qualité, en communiquant l'importance de la conformité et en s'assurant que le SMQ atteint ses résultats attendus.\n\n### Amélioration continue (§10)\nL'organisation doit continuellement améliorer l'adéquation et l'efficacité du SMQ en utilisant la politique qualité, les objectifs, les résultats d'audit, l'analyse des données et la revue de direction.\n\n## Bénéfices de la certification\n\nSelon l'enquête ISO de 2023, plus de **1,3 million d'organisations** dans 189 pays sont certifiées ISO 9001. Les bénéfices incluent :\n\n- **Amélioration de l'efficacité opérationnelle** de 20 à 30%\n- **Réduction des coûts de non-qualité** estimée entre 5 et 15% du chiffre d'affaires\n- **Augmentation de la satisfaction client** et fidélisation\n- **Accès à de nouveaux marchés** et réponse aux appels d'offres\n- **Conformité réglementaire** renforcée\n\n## Conclusion\n\nLa certification ISO 9001:2015 représente un investissement stratégique pour toute organisation souhaitant structurer sa démarche qualité et démontrer sa capacité à fournir des produits et services conformes aux exigences des clients et réglementaires."},

  {"cat":"qualite","title":"La roue de Deming PDCA : moteur de l'amélioration continue","excerpt":"Le cycle PDCA (Plan-Do-Check-Act) est la méthode fondatrice de l'amélioration continue. Apprenez à l'appliquer concrètement dans votre organisation.","content":"# La roue de Deming PDCA : moteur de l'amélioration continue\n\n## Origine et principes\n\nLe cycle **PDCA** (Plan-Do-Check-Act), également appelé **roue de Deming** du nom du statisticien William Edwards Deming, est une méthode itérative en quatre étapes pour le contrôle et l'amélioration continue des processus.\n\nDéveloppée initialement par Walter Shewhart dans les années 1930 et popularisée par Deming au Japon après la Seconde Guerre mondiale, cette méthode est devenue le fondement de la gestion de la qualité moderne.\n\n## Les 4 étapes du PDCA\n\n### PLAN — Planifier\nDéfinir ce que l'on veut accomplir :\n- L'identification du problème ou de l'opportunité d'amélioration\n- L'analyse des causes racines (diagramme d'Ishikawa, 5 Pourquoi)\n- La définition des objectifs SMART\n- L'élaboration du plan d'action avec des indicateurs mesurables\n\n### DO — Déployer\nMettre en œuvre le plan d'action sur une échelle pilote :\n- Exécuter les actions planifiées\n- Former le personnel impliqué\n- Collecter les données selon les indicateurs définis\n- Documenter les écarts éventuels\n\n### CHECK — Vérifier\nMesurer les résultats obtenus et les comparer aux objectifs :\n- Analyser les données collectées\n- Comparer les performances avant/après\n- Identifier les écarts et les causes\n- Valider ou invalider les hypothèses initiales\n\n### ACT — Agir\nStandardiser ou ajuster selon les résultats :\n- Si succès : standardiser les bonnes pratiques et former\n- Si échec partiel : ajuster et relancer un cycle PDCA\n- Capitaliser sur les leçons apprises\n- Planifier le prochain cycle d'amélioration\n\n## PDCA et normes ISO\n\nLe cycle PDCA est explicitement intégré dans la **norme ISO 9001:2015** et sert de base à toutes les normes de systèmes de management (ISO 14001, ISO 45001, ISO 22000). Il est le moteur de l'amélioration continue exigée par ces normes."},

  {"cat":"qualite","title":"Les 5S : fondement de la qualité en entreprise","excerpt":"Méthode japonaise éprouvée, les 5S (Seiri, Seiton, Seiso, Seiketsu, Shitsuke) transforment l'environnement de travail et boostent la productivité.","content":"# Les 5S : fondement de la qualité en entreprise\n\n## Qu'est-ce que les 5S ?\n\nLes **5S** sont une méthodologie d'organisation du lieu de travail d'origine japonaise, développée par Toyota dans le cadre du système de production lean.\n\n## Les 5 étapes détaillées\n\n### 1. Seiri — Trier (Débarras)\nSéparer ce qui est utile de ce qui ne l'est pas. Éliminer les outils, documents et matériaux inutiles du poste de travail.\n\n### 2. Seiton — Ranger (Ordre)\nChaque objet a sa place définie et est rangé de manière visible et accessible. Utiliser le marquage au sol, des étiquettes et des silhouettes.\n\n### 3. Seiso — Nettoyer (Propreté)\nMaintenir le poste de travail propre et identifier les sources de saleté. Établir un planning de nettoyage régulier.\n\n### 4. Seiketsu — Standardiser (Maintien en condition)\nCréer des standards et des règles pour maintenir les 3 premiers S. Rédiger des procédures et des check-lists visuelles.\n\n### 5. Shitsuke — S'impliquer (Discipline)\nFaire des 5S une habitude et une culture d'entreprise. Former et sensibiliser en continu, récompenser les bonnes pratiques.\n\n## Résultats mesurables\n\nSelon l'INRS, la mise en place des 5S permet typiquement :\n- **30% de réduction** du temps de recherche d'outils\n- **25% de réduction** des accidents de travail\n- **15% d'amélioration** de la productivité\n- **50% de réduction** des pannes matérielles"},

  {"cat":"qualite","title":"Lean Management : principes et application industrielle","excerpt":"Le Lean Management vise l'élimination des gaspillages pour maximiser la valeur ajoutée. Découvrez ses outils et sa mise en œuvre.","content":"# Lean Management : principes et application industrielle\n\n## Introduction au Lean\n\nLe **Lean Management** est une philosophie de management issue du Système de Production Toyota (TPS). Son principe fondamental est d'éliminer les **Muda** (gaspillages) pour maximiser la valeur perçue par le client.\n\n## Les 7 types de gaspillages (Muda)\n\n1. **Surproduction** — Produire plus que demandé\n2. **Attentes** — Temps d'attente entre les étapes\n3. **Transport** — Déplacements inutiles de matériaux\n4. **Surtraitement** — Opérations non demandées par le client\n5. **Stocks excessifs** — Stocker plus que le nécessaire\n6. **Mouvements inutiles** — Déplacements non productifs\n7. **Défauts** — Produits ou services non conformes\n\n## Outils du Lean\n\n### Value Stream Mapping (VSM)\nCartographie de la chaîne de valeur pour visualiser les flux et identifier les gaspillages.\n\n### Kanban\nSystème de gestion visuelle des flux qui limite le travail en cours et signale les besoins de réapprovisionnement.\n\n### Kaizen\nPhilosophie d'amélioration continue impliquant tous les collaborateurs.\n\n### 5 Pourquoi\nTechnique d'investigation pour remonter à la cause racine d'un problème.\n\n## Résultats dans l'industrie\n\n- **50% de réduction** de l'espace de stockage\n- **85% de réduction** du temps de cycle\n- **90% de réduction** du temps de mise en route\n- **50% d'amélioration** de la qualité"},

  {"cat":"qualite","title":"Audit qualité interne : méthodologie et bonnes pratiques","excerpt":"L'audit interne est un outil essentiel du SMQ. Guide complet pour planifier, réaliser et exploiter vos audits qualité selon l'ISO 19011.","content":"# Audit qualité interne : méthodologie et bonnes pratiques\n\n## Définition et objectifs\n\nL'**audit qualité interne** est un examen systématique, indépendant et documenté du système de management de la qualité. Selon la norme ISO 19011:2018, il vise à vérifier la conformité du SMQ aux exigences de la norme ISO 9001.\n\n## Méthodologie en 6 étapes\n\n### 1. Planification\nDéfinir le programme d'audit annuel, désigner les auditeurs et préparer les check-lists.\n\n### 2. Préparation\nAnalyser la documentation du processus audité, préparer les questionnaires et planifier les entretiens.\n\n### 3. Réalisation\nRéunion d'ouverture, collecte de preuves objectives (entretiens, observations, documents), vérification de la conformité.\n\n### 4. Analyse\nÉvaluer les constats, classer les non-conformités (majeure ou mineure), identifier les causes.\n\n### 5. Rapport\nRédiger le rapport d'audit, présenter les conclusions lors de la réunion de clôture, proposer des actions correctives.\n\n### 6. Suivi\nVérifier la mise en œuvre des actions correctives, évaluer leur efficacité, capitaliser sur les retours d'expérience.\n\n## Compétences de l'auditeur\n\nL'auditeur interne doit maîtriser les principes de l'audit, les exigences de la norme référentielle et les techniques d'entretien et d'observation."},

  {"cat":"qualite","title":"Coûts de la non-qualité : calcul et réduction","excerpt":"Les coûts de la non-qualité représentent jusqu'à 20% du chiffre d'affaires. Apprenez à les identifier, les mesurer et les réduire.","content":"# Coûts de la non-qualité : calcul et réduction\n\n## Définition\n\nLes **coûts de la non-qualité (CNQ)** représentent l'ensemble des coûts engagés du fait que la qualité n'est pas atteinte. Ils représentent en moyenne **10 à 20% du chiffre d'affaires**.\n\n## Catégorisation des coûts\n\n### Coûts de non-conformité (externes)\nRetours clients, garanties, pénalités de retard, perte de parts de marché.\n\n### Coûts de non-conformité (internes)\nRebuts, retouches, temps perdu, arrêts de production, stocks excessifs.\n\n### Coûts de contrôle et prévention\nInspections, audits, formation du personnel, maintenance préventive.\n\n## Indicateurs clés\n\n- **Taux de rebut** = (Quantité rebutée / Quantité produite) x 100\n- **Coût de la qualité par unité** = CNQ total / Production\n- **Ratio qualité** = (Prévention + Contrôle) / CNQ totaux\n\n## Stratégies de réduction\n\n1. Investir dans la **prévention** (formation, AMDEC)\n2. Mettre en place la **maîtrise statistique des procédés** (SPC)\n3. Appliquer les outils de **résolution de problèmes**\n4. Renforcer la **culture qualité** par l'implication de tous"},

  {"cat":"qualite","title":"Six Sigma : méthode DMAIC pour l'excellence opérationnelle","excerpt":"Six Sigma est une méthode statistique puissante pour réduire la variabilité. Découvrez la méthodologie DMAIC et ses outils.","content":"# Six Sigma : méthode DMAIC pour l'excellence opérationnelle\n\n## Qu'est-ce que Six Sigma ?\n\n**Six Sigma** vise à réduire la variabilité des processus pour atteindre **3,4 défauts par million d'opportunités (DPMO)**.\n\n## La méthodologie DMAIC\n\n### Define — Définir\nIdentifier le problème, les objectifs et les exigences clients (Voice of Customer).\n\n### Measure — Mesurer\nCartographier le processus, collecter des données fiables, calculer le niveau sigma actuel.\n\n### Analyze — Analyser\nIdentifier les causes racines, utiliser les outils statistiques (Pareto, Ishikawa), valider les hypothèses.\n\n### Improve — Améliorer\nGénérer des solutions, planifier des expériences (DOE), mettre en œuvre et valider.\n\n### Control — Contrôler\nMettre en place la surveillance (SPC), standardiser les procédures, former le personnel.\n\n## Outils statistiques clés\n\n- **Diagramme de Pareto** : Règle 80/20\n- **Diagramme d'Ishikawa** : Causes racines\n- **Carte de contrôle** : Stabilité du processus\n- **Cp/Cpk** : Capacité du processus\n\n## Bénéfices documentés\n\nGE a généré **plus de 2 milliards de dollars** d'économies avec Six Sigma entre 1996 et 2000."},

  {"cat":"qualite","title":"Maîtrise Statistique des Procédés (SPC) : guide pratique","excerpt":"La SPC permet de surveiller et maîtriser les processus de production en temps réel grâce aux cartes de contrôle.","content":"# Maîtrise Statistique des Procédés (SPC) : guide pratique\n\n## Introduction\n\nLa **SPC** utilise des outils statistiques pour surveiller et contrôler un processus de production, en distinguant les variations naturelles des variations anormales.\n\n## Les cartes de contrôle\n\n**Par variables :** X-barre et R (moyenne et étendue), X-barre et S (moyenne et écart-type)\n\n**Par attributs :** p (proportion de non-conformes), np (nombre de non-conformes), c (défauts), u (défauts par unité)\n\n## Indicateurs de capacité\n\n### Cp (Capabilité potentielle)\nCp = (TS - TI) / (6 x sigma)\n\n### Cpk (Capabilité réelle)\nCpk = min[(TS - Xbar) / (3sigma), (Xbar - TI) / (3sigma)]\n\n### Interprétation\n- Cpk >= 1,67 : Excellent (Six Sigma)\n- Cpk >= 1,33 : Capable\n- Cpk >= 1,00 : Minimum acceptable\n- Cpk < 1,00 : Non capable\n\n## Application pratique\n\nLa SPC est utilisée dans l'automobile, l'aéronautique, la pharmacie et l'agroalimentaire pour surveiller les caractéristiques critiques des produits en temps réel."},

  {"cat":"qualite","title":"AMDEC : Analyse des Modes de Défaillance et de leurs Effets","excerpt":"L'AMDEC est un outil d'analyse préventive essentiel pour identifier les risques de défaillance et définir des actions de mitigation.","content":"# AMDEC : Analyse des Modes de Défaillance et de leurs Effets\n\n## Définition\n\nL'**AMDEC** est une méthode d'analyse préventive qui permet d'identifier les défaillances potentielles, d'évaluer leurs impacts et de définir des actions correctives.\n\n## Types d'AMDEC\n\n- **AMDEC produit** : Défaillances du produit fini\n- **AMDEC processus** : Défaillances des étapes de production\n- **AMDEC moyen** : Défaillances des équipements\n\n## Méthodologie\n\n### Calcul de la criticité (IPR)\n**IPR = G x F x D**\n- **G** (Gravité) : Sévérité de l'effet (1 à 10)\n- **F** (Fréquence) : Probabilité d'occurrence (1 à 10)\n- **D** (Détection) : Capacité de détection (1 à 10)\n\n### Actions correctives\nPour les IPR > 100 :\n- Réduire la gravité (conception de sécurité)\n- Réduire la fréquence (maintenance préventive)\n- Améliorer la détection (capteurs, contrôles)\n\n## Types de défaillance\n\n- Perte de fonction\n- Fonctionnement intempestif\n- Fonctionnement dégradé\n- Refus de fonctionner\n\nL'AMDEC est un document vivant à mettre à jour régulièrement."},

  {"cat":"qualite","title":"Kaizen : la philosophie de l'amélioration continue au quotidien","excerpt":"Le Kaizen transforme la culture d'entreprise en impliquant chaque collaborateur dans l'amélioration continue.","content":"# Kaizen : la philosophie de l'amélioration continue au quotidien\n\n## Origine\n\n**Kaizen** (改善) signifie littéralement \"changement pour le mieux\". Développé par Masaaki Imai, cette philosophie repose sur l'idée que toute amélioration, même petite, contribue à l'excellence.\n\n## Les 10 principes du Kaizen\n\n1. **Abolir les excuses** : Chercher des solutions, pas des justifications\n2. **Penser positif** : Croire en l'amélioration\n3. **Ne pas chercher la perfection immédiate** : Un pas après l'autre\n4. **Corriger immédiatement les erreurs**\n5. **Ne pas dépenser pour résoudre** : Utiliser la créativité\n6. **Utiliser la sagesse plutôt que l'argent**\n7. **Comprendre la racine du problème**\n8. **Demander \"Pourquoi ?\" 5 fois**\n9. **Considérer les idées de chacun**\n10. **L'amélioration n'a pas de fin**\n\n## Types de Kaizen\n\n### Kaizen de routine\nAméliorations quotidiennes par les opérateurs (cercles de qualité).\n\n### Kaizen de projet\nÉvénements structurés de 3 à 5 jours avec une équipe dédiée.\n\n### Kaizen de gestion\nAméliorations au niveau des processus de support (RH, comptabilité).\n\n## Événement Kaizen en 5 jours\n\n1. **Jour 1** : Formation et diagnostic\n2. **Jour 2** : Analyse des causes et brainstorming\n3. **Jour 3** : Mise en œuvre des solutions\n4. **Jour 4** : Vérification et ajustements\n5. **Jour 5** : Standardisation et présentation"},

  # ══════════ HYGIENE (10) ══════════
  {"cat":"hygiene","title":"HACCP : les 7 principes fondamentaux de la sécurité alimentaire","excerpt":"Le système HACCP est la méthode de référence mondiale pour la maîtrise des dangers alimentaires. Découvrez ses 7 principes.","content":"# HACCP : les 7 principes fondamentaux de la sécurité alimentaire\n\n## Introduction\n\nLe **HACCP** (Hazard Analysis Critical Control Points) est un système préventif de gestion de la sécurité alimentaire, reconnu par le **Codex Alimentarius** de la FAO/OMS.\n\n## Les 7 principes\n\n### Principe 1 : Analyse des dangers\nIdentifier tous les dangers potentiels (biologiques, chimiques, physiques) à chaque étape du processus.\n\n### Principe 2 : Détermination des CCP\nIdentifier les étapes où un contrôle peut prévenir, éliminer ou réduire un danger à un niveau acceptable.\n\n### Principe 3 : Limites critiques\nDéfinir les valeurs limites (ex: température >= 72°C pendant 15 secondes, pH <= 4.6).\n\n### Principe 4 : Procédures de surveillance\nDéfinir comment et à quelle fréquence chaque CCP sera surveillé (capteurs, mesures horaires).\n\n### Principe 5 : Actions correctives\nDéterminer les actions quand un CCP n'est pas maîtrisé, incluant le traitement du produit non conforme.\n\n### Principe 6 : Vérification\nConfirmer que le système fonctionne (validation, audits internes, analyses microbiologiques).\n\n### Principe 7 : Documentation\nTenir des enregistrements complets pour la traçabilité et la conformité réglementaire.\n\n## Cadre réglementaire\n\nAu Maroc, l'**ONSSA** encadre le HACCP. L'UE l'exige pour toutes les entreprises alimentaires (Règlement CE 852/2004)."},

  {"cat":"hygiene","title":"Sécurité alimentaire : de la ferme à l'assiette","excerpt":"La sécurité alimentaire couvre l'ensemble de la chaîne alimentaire. Comprendre les enjeux de la production à la consommation.","content":"# Sécurité alimentaire : de la ferme à l'assiette\n\n## Les dangers alimentaires\n\n### Dangers biologiques\nBactéries (Salmonella, Listeria, E. coli), virus (Norovirus, hépatite A), parasites (Toxoplasma, Anisakis), mycotoxines.\n\n### Dangers chimiques\nRésidus de pesticides, additifs non conformes, métaux lourds, allergènes non déclarés.\n\n### Dangers physiques\nFragments de verre, métal, plastique, pierres, os.\n\n## La chaîne de contrôle\n\n1. **Production primaire** : Maîtrise des intrants\n2. **Transformation** : Application du HACCP, BPH\n3. **Conditionnement** : Emballages conformes, étiquetage\n4. **Stockage et transport** : Maîtrise du froid\n5. **Distribution** : Respect des températures\n6. **Restauration** : Formation et hygiène des manipulations\n\n## Prévention des toxi-infections\n\nLe respect de la chaîne du froid et des règles d'hygiène permet de prévenir la majorité des toxi-infections alimentaires, qui représentent plus de 500 000 cas par an en France selon l'EFSA."},

  {"cat":"hygiene","title":"Bonnes Pratiques d'Hygiène (BPH) en industrie alimentaire","excerpt":"Les BPH sont les prérequis indispensables au HACCP. Guide des exigences en matière d'hygiène alimentaire.","content":"# Bonnes Pratiques d'Hygiène (BPH) en industrie alimentaire\n\n## Exigences des BPH\n\n### 1. Hygiène du personnel\nFormation obligatoire, tenue propre (charlotte, masque, gants), lavage des mains régulier, examen médical, comportement approprié.\n\n### 2. Conception des locaux\nZonage (zones propres/sales), surfaces lavesables, ventilation avec filtration, éclairage suffisant, évacuation des eaux sans stagnation.\n\n### 3. Maîtrise des nuisibles\nProgramme de dératisation/désinsectisation, barrières physiques, monitoring régulier, sociétés agréées.\n\n### 4. Nettoyage et désinfection\nPlan de N&D documenté, produits autorisés et dosés, validation par analyses microbiologiques, traçabilité des opérations.\n\n### 5. Gestion des déchets\nCollecte et élimination régulières, poubelles fermées et identifiées, zones de stockage dédiées.\n\n## Normes de référence\n\nLes BPH sont détaillées dans le **Codex Alimentarius** (CAC/RCP 1-1969) et les guides sectoriels nationaux publiés par les autorités compétentes."},

  {"cat":"hygiene","title":"Traçabilité alimentaire : enjeux et systèmes","excerpt":"La traçabilité permet de suivre un produit à toutes les étapes. Découvrez les systèmes et les obligations réglementaires.","content":"# Traçabilité alimentaire : enjeux et systèmes\n\n## Définition\n\nLa **traçabilité alimentaire** est la capacité à retracer le parcours d'un produit, de ses matières premières jusqu'au produit fini, et inversement.\n\n## Cadre réglementaire\n\n- **Règlement CE 178/2002** (UE) : Identification des fournisseurs et clients\n- **ISO 22005:2007** : Principes pour la traçabilité dans la chaîne alimentaire\n- **Loi 28-07** (Maroc) : Sécurité sanitaire et ONSSA\n\n## Technologies utilisées\n\n- **Codes-barres et QR codes** : Identification rapide\n- **RFID** : Suivi en temps réel\n- **Blockchain** : Traçabilité transparente et infalsifiable\n- **Logiciels ERP** : Gestion des lots\n\n## Gestion des crises\n\nEn cas de contamination, la traçabilité permet :\n- Identifier rapidement les produits concernés\n- Localiser les lots dans la distribution\n- Procéder au retrait du marché en < 24h\n- Informer consommateurs et autorités"},

  {"cat":"hygiene","title":"ISO 22000 : système de management de la sécurité alimentaire","excerpt":"La norme ISO 22000 intègre le HACCP dans un cadre de management global. Découvrez ses exigences et la certification.","content":"# ISO 22000 : système de management de la sécurité alimentaire\n\n## Présentation\n\nLa norme **ISO 22000:2018** définit les exigences d'un système de management de la sécurité des denrées alimentaires (SMSDA), applicable à toute la chaîne alimentaire.\n\n## Structure\n\n### Prérequis Programmes (PRP)\nConditions de base (BPH) et conditions opérationnelles pour un environnement de production sûr.\n\n### Principes du HACCP\nIntégration des 7 principes du Codex Alimentarius avec validation et vérification renforcée.\n\n### Management de la sécurité\nPolitique de sécurité alimentaire, équipe multidisciplinaire, objectifs mesurables, communication interne et externe.\n\n## Étapes de certification\n\n1. Diagnostic initial\n2. Mise en place des PRP\n3. Analyse des dangers\n4. Détermination des CCP\n5. Système documentaire\n6. Formation du personnel\n7. Audit interne\n8. Certification par organisme accrédité\n\n## Bénéfices\n\nAccès aux marchés internationaux, confiance des partenaires, réduction des crises alimentaires, conformité réglementaire."},

  {"cat":"hygiene","title":"Allergènes alimentaires : gestion et étiquetage","excerpt":"Les allergènes alimentaires touchent 3-4% de la population adulte. La maîtrise des allergènes est critique pour la sécurité.","content":"# Allergènes alimentaires : gestion et étiquetage\n\n## L'enjeu\n\nLes **allergènes alimentaires** provoquent des réactions pouvant être fatales (anaphylaxie). Ils touchent **3-4% des adultes** et **6-8% des enfants**.\n\n## Les 14 allergènes majeurs (UE)\n\nGluten, crustacés, œufs, poissons, arachides, soja, lait, fruits à coque, céleri, moutarde, sésame, sulfites, lupin, mollusques.\n\n## Gestion en production\n\n### Prévention de la contamination croisée\nSéparation des lignes, nettoyage validé par tests de détection, tenue spécifique du personnel.\n\n### Étiquetage\nDéclaration obligatoire en gras, avertissement de présence fortuite (\"Peut contenir des traces de...\"), liste complète des ingrédients.\n\n### Formation\nReconnaître les symptômes d'une réaction allergique, connaître les protocoles d'urgence, comprendre les risques de contamination croisée."},

  {"cat":"hygiene","title":"Nettoyage et désinfection en industrie agroalimentaire","excerpt":"Le nettoyage-désinfection (N&D) est un prérequis essentiel. Protocoles, produits et validation de l'efficacité.","content":"# Nettoyage et désinfection en industrie agroalimentaire\n\n## Méthodologie en 5 étapes\n\n### 1. Pré-rinçage\nÉliminer les résidus à l'eau claire (réduction de 80-90% de la charge).\n\n### 2. Nettoyage (détergence)\nDétergents alcalins (graisses), acides (tartres), neutres (salissures légères).\n\n### 3. Rinçage intermédiaire\nÉliminer les résidus de détergent, vérification pH et conductivité.\n\n### 4. Désinfection\nChlorés, peroxydés (acide peracétique), ammoniums quaternaires.\n\n### 5. Rinçage final\nObligatoire pour les produits en contact direct avec les aliments.\n\n## Validation\n\n### Contrôles microbiologiques\nPrélèvements de surface (écouvillons), analyse ATP-métrie (< 15 secondes).\n\n### Seuils d'acceptation\n< 10 UFC/cm² pour les surfaces en contact direct.\n\n### Indicateurs\nTaux de conformité des analyses, temps moyen de N&D, consommation de produits."},

  {"cat":"hygiene","title":"Hygiène et sécurité en restauration collective","excerpt":"La restauration collective nécessite des mesures d'hygiène strictes. Guide des bonnes pratiques pour cantines et hôpitaux.","content":"# Hygiène et sécurité en restauration collective\n\n## Contexte\n\nLa restauration collective concerne les cantines scolaires, restaurants d'entreprise et hôpitaux, touchant des populations vulnérables.\n\n## Températures réglementaires\n\n| Produit | Température |\n|---------|------------|\n| Produits frais | +4°C max |\n| Surgelés | -18°C max |\n| Aliments chauds | +63°C |\n\n## Règle des 2 heures\n\nTout aliment sorti du froid doit être remis au froid ou consommé dans les 2 heures.\n\n## Gestion des repas\n\n- **Préparation** : Respect des durées de vieillissement\n- **Transport** : Véhicules frigorifiques avec enregistrement\n- **Service** : Distribution dans les 2 heures\n- **Restes** : Interdiction de resservir les plats déjà servis\n\n## Formation obligatoire\n\nTout le personnel de cuisine doit être formé aux règles d'hygiène et au HACCP selon la réglementation en vigueur."},

  {"cat":"hygiene","title":"Contrôle sanitaire des denrées alimentaires","excerpt":"Le contrôle sanitaire garantit la conformité des produits. Microbiologie, chimie et inspections.","content":"# Contrôle sanitaire des denrées alimentaires\n\n## Analyses microbiologiques\n\n### Flore totale (aérobies mésophiles)\n< 10⁵ UFC/g (produits frais), < 10³ UFC/g (stérilisés).\n\n### Indicateurs fécaux\nColiformes, E. coli, entérocoques.\n\n### Pathogènes\nSalmonella (absence/25g), Listeria (< 100 UFC/g), S. aureus (< 10³ UFC/g).\n\n## Critères réglementaires\n\n### Critères de sécurité\nNe doivent pas être dépassés (retrait du produit).\n\n### Critères d'hygiène des processus\nIndicateurs pour évaluer l'hygiène de production (actions correctives).\n\n## Plan de contrôle\n\n- **Quotidien** : pH, température, ATP\n- **Hebdomadaire** : Flore totale, coliformes\n- **Mensuelle** : Recherche de pathogènes\n- **Trimestrielle** : Analyses chimiques\n\nLes analyses doivent être réalisées par des laboratoires accrédités **ISO 17025**."},

  {"cat":"hygiene","title":"Hygiène au travail : prévention des risques professionnels","excerpt":"L'hygiène au travail protège la santé des travailleurs dans tous les secteurs. Risques, VLE et mesures de prévention.","content":"# Hygiène au travail : prévention des risques professionnels\n\n## Risques par secteur\n\n### Industrie chimique\nSubstances toxiques, dermatoses, nanomatériaux.\n\n### BTP\nSilice cristalline (silicose), amiante, bruits et vibrations.\n\n### Secteur médical\nRisques biologiques, rayonnements ionisants, TMS.\n\n## Valeurs Limites d'Exposition\n\n### VLE-PT (Plafond)\nNe doit jamais être dépassée. Ex: Plomb = 0,15 mg/m³.\n\n### VLE-8h (Moyenne pondérée)\nSur 8 heures. Ex: Benzène = 1 ppm.\n\n## Mesures de prévention\n\n### Élimination et substitution\nRemplacer les produits dangereux par des alternatives moins nocives.\n\n### Protection collective\nVentilation, captage à la source, encoffrements.\n\n### Protection individuelle\nEPI adaptés : masques, gants, lunettes, vêtements de protection.\n\n### Surveillance médicale\nVisites médicales régulières, biométrologie, fiches d'exposition."},
]

# ════════════ SECURITE (need 3 more to reach 10) ═══════════
articles += [
  {"cat":"securite","title":"Analyse des risques professionnels : méthodes et outils","excerpt":"L'analyse des risques est la base de la prévention. Découvrez les principales méthodes : HIRA, arbre des causes, nœud papillon.","content":"# Analyse des risques professionnels : méthodes et outils\n\n## Pourquoi analyser les risques ?\n\nL'analyse des risques professionnels est une obligation légale (Code du travail marocain, Directive européenne 89/391/CEE). Elle permet d'identifier, d'évaluer et de hiérarchiser les risques pour définir des actions de prévention adaptées.\n\n## Principales méthodes\n\n### HIRA (Hazard Identification and Risk Assessment)\nMéthode systématique en 5 étapes : identification des dangers, évaluation de la gravité et de la probabilité, détermination du niveau de risque, définition des mesures de contrôle.\n\n### Diagramme d'Ishikawa (causes-effet)\nClassement des causes par familles : Matière, Main-d'œuvre, Matériel, Méthode, Milieu, Mesure (5M).\n\n### Méthode du nœud papillon\nReprésentation graphique des événements indésirables, des causes potentielles et des conséquences, avec les barrières de prévention et de protection.\n\n### Matrice des risques\nCroisement de la probabilité d'occurrence (1-5) et de la gravité (1-5) pour obtenir un niveau de risque (1-25).\n\n## Hiérarchisation des mesures de prévention\n\n1. **Élimination** du danger\n2. **Substitution** par un agent moins dangereux\n3. **Protections techniques** collectives\n4. **Protections individuelles** (EPI)\n5. **Formations et procédures**"},

  {"cat":"securite","title":"Gestion des situations d'urgence en entreprise","excerpt":"La préparation aux situations d'urgence sauve des vies. Plan d'évacuation, premiers secours et gestion de crise.","content":"# Gestion des situations d'urgence en entreprise\n\n## Pourquoi se préparer ?\n\nLes situations d'urgence en entreprise (incendie, accident grave, fuite chimique) nécessitent une préparation rigoureuse. Selon l'INRS, une entreprise préparée réduit de **80%** les conséquences d'un sinistre.\n\n## Le plan d'évacuation\n\n### Éléments obligatoires\n- Plans d'évacuation affichés et visibles\n- Chemins d'évacuation dégagés et signalisés\n- Sorties de secours clairement identifiées\n- Point de rassemblement défini et communiqué\n- Personnes désignées pour guider l'évacuation\n\n### Exercices d'évacuation\nAu minimum 1 exercice par an pour tous les occupants, avec chronométrage et retour d'expérience.\n\n## Les premiers secours\n\n### Gestes de premiers secours\n- **PDS** : Protéger, Déplacer/Donner l'alerte, Secourir\n- **PAC** : Protection, Alerte, Conduite à tenir\n- Utilisation du **DAE** (Défibrillateur Automatisé Externe)\n- Conduite à tenir face à un saignement, une brûlure, un malaise\n\n## Les équipements d'urgence\n\n- Extincteurs (adaptés au risque : eau, CO2, poudre)\n- Systèmes d'alarme sonore et visuelle\n- Détection incendie (fumée, chaleur)\n- Trousse de premiers secours\n- DAE accessible en moins de 3 minutes"},

  {"cat":"securite","title":"Les Équipements de Protection Individuelle (EPI) : guide complet","excerpt":"Les EPI sont la dernière ligne de défense du travailleur. Guide de sélection, utilisation et entretien des EPI.","content":"# Les Équipements de Protection Individuelle (EPI) : guide complet\n\n## Définition\n\nUn **EPI** est un dispositif porté par le travailleur pour le protéger contre un ou plusieurs risques professionnels. C'est la dernière barrière de protection dans la hiérarchie des mesures de prévention.\n\n## Catégories de risque\n\n### Catégorie I (risques mineurs)\nProtection contre les agressions superficielles (gants de jardinage, lunettes solaires).\n\n### Catégorie II (risques sérieux)\nProtection contre des risques significatifs (casques, gants chimiques, protections auditives).\n\n### Catégorie III (risques mortels)\nProtection contre les dangers de mort ou de lésions irréversibles (harnais de sécurité, appareils respiratoires, combinaisons anti-chimiques).\n\n## Principaux types d'EPI\n\n### Protection de la tête\nCasques de sécurité (EN 397), coiffes et charlottes anti-choc.\n\n### Protection des yeux et du visage\nLunettes de sécurité (EN 166), écrans faciaux, masques à souder.\n\n### Protection auditive\nBouchons d'oreilles (EN 352-2), casques anti-bruit (EN 352-1).\n\n### Protection respiratoire\nMasques FFP1/FFP2/FFP3, demi-masques, masques complets, appareils à adduction d'air.\n\n### Protection des mains\nGants contre les risques mécaniques (EN 388), chimiques (EN 374), thermiques (EN 407).\n\n### Protection des pieds\nChaussures de sécurité (EN ISO 20345) avec embout de protection composite ou acier.\n\n## Obligations de l'employeur\n\n- Fournir gratuitement les EPI adaptés\n- Former le personnel à leur utilisation\n- Vérifier leur bon état et leur maintenance\n- Remplacer les EPI usés ou périmés"},
]

# ════════════ ENVIRONNEMENT (need 8 more) ═══════════
articles += [
  {"cat":"environnement","title":"ISO 14001:2015 : le système de management environnemental","excerpt":"La norme ISO 14001:2015 est le standard international pour la gestion environnementale. Découvrez ses exigences et bénéfices.","content":"# ISO 14001:2015 : le système de management environnemental\n\n## Présentation\n\nLa norme **ISO 14001:2015** définit les exigences d'un système de management environnemental (SME) permettant à une organisation d'améliorer ses performances environnementales de manière structurée.\n\n## Structure SHS (Clauses 1-10)\n\n1. **Contexte** : Identifier les enjeux environnementaux internes et externes\n2. **Leadership** : Engagement de la direction pour la protection de l'environnement\n3. **Planification** : Aspects et impacts environnementaux, obligations de conformité\n4. **Support** : Ressources, compétences, sensibilisation, communication\n5. **Réalisation opérationnelle** : Maîtrise opérationnelle, préparation aux situations d'urgence\n6. **Évaluation** : Surveillance, mesure, audit interne, revue de direction\n7. **Amélioration** : Non-conformités, actions correctives, amélioration continue\n\n## Aspects et impacts environnementaux\n\nL'organisation doit identifier ses aspects environnementaux (éléments de ses activités qui interagissent avec l'environnement) et évaluer leurs impacts significatifs.\n\n### Exemples d'aspects\n- Émissions atmosphériques (CO2, NOx, particules)\n- Rejets d'eaux usées\n- Production de déchets\n- Consommation d'énergie et de matières premières\n- Utilisation des sols\n- Pollutions sonores\n\n## Bénéfices\n\n- Réduction de la consommation d'énergie de **15 à 30%**\n- Réduction des déchets de **20 à 40%**\n- Conformité réglementaire renforcée\n- Amélioration de l'image de marque"},

  {"cat":"environnement","title":"Gestion des déchets : de la réduction au recyclage","excerpt":"La gestion des déchets est un enjeu environnemental majeur. Découvrez la hiérarchie des déchets et les bonnes pratiques.","content":"# Gestion des déchets : de la réduction au recyclage\n\n## La hiérarchie des 5R\n\n1. **Refuser** : Ne pas acquérir ce dont on n'a pas besoin\n2. **Réduire** : Minimiser les quantités à la source\n3. **Réutiliser** : Donner une seconde vie aux objets\n4. **Recycler** : Transformer les déchets en matières premières\n5. **Composter** : Valoriser la matière organique\n\n## Cadre réglementaire marocain\n\nLa **loi 28-00** relative à la gestion des déchets et son décret d'application définissent les obligations des producteurs et détenteurs de déchets.\n\n## Types de déchets\n\n### Déchets ménagers et assimilés\nOrdures ménagères, encombrants, déchets verts.\n\n### Déchets industriels\nDéchets industriels banals (DIB) et déchets industriels spéciaux (DIS).\n\n### Déchets dangereux\nProduits chimiques, solvants, piles, huiles usagées.\n\n### Déchets d'activités de soins\nDéchets d'activités de soins à risques infectieux (DASRI).\n\n## Bonnes pratiques en entreprise\n\n- Tri sélectif à la source avec bacs colorés\n- Réduction à la source (éco-conception)\n- Contrats avec des prestataires agréés\n- Suivi quantitatif des gisements\n- Sensibilisation du personnel"},

  {"cat":"environnement","title":"Développement durable : les 3 piliers en entreprise","excerpt":"Le développement durable équilibre économie, environnement et social. Comment l'intégrer dans la stratégie d'entreprise.","content":"# Développement durable : les 3 piliers en entreprise\n\n## Définition\n\nLe **développement durable** est un développement qui répond aux besoins du présent sans compromettre la capacité des générations futures à répondre aux leurs (Rapport Brundtland, 1987).\n\n## Les 3 piliers\n\n### Pilier environnemental\nProtection de l'environnement, lutte contre le changement climatique, préservation de la biodiversité, gestion durable des ressources naturelles.\n\n### Pilier social\nRespect des droits de l'homme, conditions de travail décentes, santé et sécurité au travail, diversité et inclusion, développement des compétences.\n\n### Pilier économique\nPerformance financière responsable, création d'emplois, innovation durable, chaîne d'approvisionnement éthique.\n\n## Les 17 ODD de l'ONU\n\nLes **Objectifs de Développement Durable** fournissent un cadre d'action mondial à l'horizon 2030 : pas de pauvreté, faim zéro, bonne santé, éducation, égalité, eau propre, énergie propre, etc.\n\n## RSE (Responsabilité Sociétale des Entreprises)\n\nLa norme **ISO 26000** fournit des lignes directrices pour la RSE. Elle couvre la gouvernance, les droits de l'homme, les pratiques d'emploi, l'environnement, les bonnes pratiques des affaires, les questions de consommation et l'engagement sociétal."},

  {"cat":"environnement","title":"Évaluation environnementale des projets et activités","excerpt":"L'évaluation environnementale permet d'anticiper les impacts d'un projet sur l'environnement. Études d'impact et procédures.","content":"# Évaluation environnementale des projets et activités\n\n## Pourquoi évaluer ?\n\nL'évaluation environnementale permet d'identifier, de décrire et d'évaluer les effets d'un projet sur l'environnement avant sa réalisation, afin de les intégrer dans la prise de décision.\n\n## Types d'évaluations\n\n### Étude d'Impact sur l'Environnement (EIE)\nObligatoire pour les projets à forts impacts (industries, infrastructures, carrières). Elle comprend : état initial, analyse des impacts, mesures d'atténuation, plan de gestion environnementale.\n\n### Notice d'impact\nPour les projets à impacts modérés, document simplifié décrivant les effets et les mesures de réduction.\n\n### Audit environnemental\nÉvaluation systématique et périodique des performances environnementales d'une organisation existante.\n\n## Méthodologie\n\n1. **Délimitation du périmètre** d'étude\n2. **État initial** du milieu (air, eau, sol, biodiversité, paysage)\n3. **Identification des impacts** potentiels (positifs et négatifs)\n4. **Évaluation de la significativence** des impacts\n5. **Mesures d'atténuation** proposées\n6. **Plan de surveillance** environnementale\n\n## Cadre réglementaire marocain\n\nLa **loi 13-03** relative aux EIE et ses décrets d'application définissent les catégories de projets soumis à EIE et la procédure d'examen et d'approbation."},

  {"cat":"environnement","title":"Efficacité énergétique en entreprise : stratégies et bonnes pratiques","excerpt":"L'efficacité énergétique réduit les coûts et les émissions de CO2. Découvrez les stratégies pour une entreprise éco-énergétique.","content":"# Efficacité énergétique en entreprise : stratégies et bonnes pratiques\n\n## Pourquoi améliorer l'efficacité énergétique ?\n\nLa facture énergétique représente **10 à 30%** des coûts opérationnels d'une entreprise industrielle. L'efficacité énergétique permet de réduire ces coûts tout en diminuant l'empreinte carbone.\n\n## Diagnostic énergétique\n\n### Étude des consommations\nAnalyser les factures d'énergie, installer des compteurs divisionnaires, établir le bilan énergétique par poste de consommation.\n\n### Identification des gisements d'économie\nComparer les consommations avec les benchmarks sectoriels, identifier les postes les plus énergivores.\n\n## Stratégies d'amélioration\n\n### Bâtiment\n- Isolation thermique des parois et toitures\n- Fenêtres à double/triple vitrage\n- Éclairage LED (réduction de 50 à 80%)\n- Gestion intelligente du chauffage/climatisation\n\n### Processus de production\n- Optimisation des procédés thermiques\n- Récupération de chaleur fatale\n- Variation de vitesse des moteurs (variateurs)\n- Maintenance énergétique des équipements\n\n### Énergies renouvelables\n- Panneaux solaires photovoltaïques\n- Solaire thermique pour l'eau chaude\n- Pompes à chaleur\n- Éolien de petite puissance\n\n## Norme ISO 50001\n\nLa **norme ISO 50001** fournit un cadre pour établir un système de management de l'énergie (SMEn), incluant politique énergétique, planification, mise en œuvre, vérification et amélioration."},

  {"cat":"environnement","title":"Pollution de l'air : sources, impacts et prévention","excerpt":"La pollution de l'air est un enjeu sanitaire et environnemental majeur. Sources, réglementation et mesures de prévention.","content":"# Pollution de l'air : sources, impacts et prévention\n\n## Sources de pollution\n\n### Sources industrielles\nÉmissions de CO2, SO2, NOx, particules (PM10, PM2.5), COV (composés organiques volatils) liées aux processus de combustion, aux stockages et aux transports.\n\n### Sources mobiles\nVéhicules, engins de chantier, navires et aéronefs.\n\n### Sources agricoles\nAmmoniac, pesticides, émissions de méthane (élevage).\n\n## Impacts sanitaires\n\nL'OMS estime que la pollution de l'air est responsable de **7 millions de décès prématurés** par an dans le monde. Les pathologies incluent maladies respiratoires, cardiovasculaires et cancers.\n\n## Cadre réglementaire\n\n### Maroc\nLa loi 13-03 relative à la lutte contre la pollution de l'air et ses décrets d'application fixent les valeurs limites d'émission pour les sources fixes.\n\n### UE\nDirective 2008/50/CE sur la qualité de l'air ambiant, réglementation IED (Emissions Industrielles).\n\n## Mesures de prévention\n\n- **Dépoussiéreurs** : Filtres à manches, électrofiltres, cyclones\n- **Désulfurisation** : Procédés humides et secs\n- **Réduction des NOx** : Sélective catalytic reduction (SCR)\n- **Monitoring** : Mesure en continu des émissions"},

  {"cat":"environnement","title":"Gestion de l'eau : un enjeu vital pour les entreprises","excerpt":"La gestion durable de l'eau est devenue un impératif. Économies, traitement et réutilisation des eaux industrielles.","content":"# Gestion de l'eau : un enjeu vital pour les entreprises\n\n## Contexte\n\nLe Maroc fait face à un stress hydrique croissant avec moins de **500 m³/habitant/an** (seuil de pénurie : 1000 m³). La gestion rationnelle de l'eau est un enjeu stratégique pour les entreprises.\n\n## Consommation d'eau par secteur\n\n- **Industrie agroalimentaire** : 10 à 50 m³/tonne produite\n- **Industrie textile** : 100 à 200 m³/tonne\n- **Métallurgie** : 20 à 60 m³/tonne\n- **Papeterie** : 10 à 50 m³/tonne\n\n## Stratégies d'économie d'eau\n\n### Optimisation des procédés\n- Réduction des pertes en ligne\n- Recyclage des eaux de processus\n- Systèmes de lavage fermés\n- Nettoyage CIP (Clean-In-Place)\n\n### Réutilisation des eaux usées traitées\n- Eaux grises pour les toilettes et l'arrosage\n- Traitement par osmose inverse\n- Filtration membranaire\n- UV et chloration pour la désinfection\n\n### Eaux pluviales\n- Récupération pour l'arrosage et le nettoyage\n- Infiltration pour la recharge des nappes\n- Puits d'infiltration et toits végétalisés\n\n## Cadre réglementaire\n\nLa **loi 10-95** sur l'eau définit les conditions d'utilisation des ressources hydriques et les normes de rejet des eaux usées industrielles."},

  {"cat":"environnement","title":"Empreinte carbone : calcul et réduction pour les entreprises","excerpt":"L'empreinte carbone mesure les émissions de GES d'une organisation. Apprenez à la calculer et à la réduire selon les normes.","content":"# Empreinte carbone : calcul et réduction pour les entreprises\n\n## Définition\n\nL'**empreinte carbone** mesure la totalité des émissions de gaz à effet de serre (GES) directement ou indirectement générées par une activité, un produit ou une organisation.\n\n## Les 3 scopes du GHG Protocol\n\n### Scope 1 (Émissions directes)\nCombustion de carburants, flotte de véhicules, procédés industriels, fuites de réfrigérants.\n\n### Scope 2 (Émissions indirectes liées à l'énergie)\nÉlectricité achetée, vapeur, chauffage et climatisation.\n\n### Scope 3 (Autres émissions indirectes)\nChaîne d'approvisionnement, déplacements professionnels, traitement des déchets, utilisation des produits vendus.\n\n## Méthodes de calcul\n\n### Bilan Carbone (ADEME)\nMéthode française simplifiée applicable à toutes les organisations.\n\n### ISO 14064-1\nNorme internationale pour la quantification et le rapport des émissions de GES.\n\n### GHG Protocol\nRéférence mondiale avec les 3 scopes et les facteurs d'émission.\n\n## Stratégies de réduction\n\n1. **Efficacité énergétique** : Réduire la consommation\n2. **Énergies renouvelables** : Transition vers des sources bas carbone\n3. **Mobilité durable** : Télétravail, vélo, transports en commun\n4. **Éco-conception** : Réduire l'impact des produits\n5. **Compensation carbone** : Projets de séquestration ou d'énergies renouvelables"},
]

# ════════════ MANAGEMENT QHSE (need 5 more) ═══════════
articles += [
  {"cat":"management","title":"Système de Management Intégré (SMI) : QSE unifié","excerpt":"Le SMI combine qualité, sécurité et environnement en un seul système. Découvrez les avantages et la mise en œuvre.","content":"# Système de Management Intégré (SMI) : QSE unifié\n\n## Définition\n\nUn **Système de Management Intégré (SMI)** combine deux ou plusieurs systèmes de management (qualité, sécurité, environnement) en un seul système cohérent pour améliorer l'efficacité globale.\n\n## Normes intégrables\n\n- **ISO 9001** : Management de la qualité\n- **ISO 14001** : Management environnemental\n- **ISO 45001** : Management de la santé et sécurité au travail\n\nCes trois normes partagent la même **Structure de Haut Niveau (SHS)**, facilitant leur intégration.\n\n## Avantages du SMI\n\n### Efficacité opérationnelle\n- **30% de réduction** des audits (audit unique au lieu de 3)\n- **40% de réduction** de la documentation redondante\n- **25% d'amélioration** de l'efficacité des processus\n\n### Cohérence stratégique\n- Vision transversale des risques et opportunités\n- Politique et objectifs intégrés\n- Communication interne unifiée\n\n### Réduction des coûts\n- Moins de ressources pour la gestion documentaire\n- Formation unique sur les exigences communes\n- Amélioration continue mutualisée\n\n## Mise en œuvre en 8 étapes\n\n1. Diagnostic des systèmes existants\n2. Analyse des exigences communes et spécifiques\n3. Définition du périmètre du SMI\n4. Cartographie des processus transversaux\n5. Documentation intégrée\n6. Formation du personnel\n7. Audit intégré\n8. Certification multi-référentielle"},

  {"cat":"management","title":"L'audit QHSE : un outil stratégique de pilotage","excerpt":"L'audit QHSE évalue la conformité et l'efficacité des systèmes de management. Méthodologie, types d'audit et exploitation des résultats.","content":"# L'audit QHSE : un outil stratégique de pilotage\n\n## Définition\n\nL'**audit QHSE** est un examen méthodique et indépendant du système de management intégré, évaluant la conformité aux normes ISO 9001, ISO 14001 et ISO 45001.\n\n## Référentiel : ISO 19011:2018\n\nCette norme fournit les lignes directrices pour l'audit des systèmes de management, applicable à tous les types d'audits et toutes les normes SHS.\n\n## Types d'audits QHSE\n\n### Audit intégré\nÉvalue simultanément les 3 systèmes (Q, S, E) en une seule mission.\n\n### Audit de conformité\nVérifie la conformité aux exigences réglementaires et normatives.\n\n### Audit de performance\nÉvalue l'efficacité du système à atteindre les objectifs fixés.\n\n## Processus d'audit\n\n1. **Programme d'audit** : Planification annuelle des audits\n2. **Préparation** : Check-lists, revue documentaire\n3. **Exécution** : Entretiens, observations, analyses documentaires\n4. **Rapport** : Constats, non-conformités, opportunités d'amélioration\n5. **Suivi** : Vérification des actions correctives\n\n## Compétences de l'auditeur QHSE\n\n- Connaissance des 3 référentiels normatifs\n- Maîtrise des techniques d'audit\n- Compétence dans le domaine d'activité audité\n- Indépendance et impartialité\n- Capacités relationnelles et de communication"},

  {"cat":"management","title":"Veille réglementaire QHSE : méthode et outils","excerpt":"La veille réglementaire permet d'anticiper les évolutions légales. Découvrez les méthodes pour rester en conformité.","content":"# Veille réglementaire QHSE : méthode et outils\n\n## Pourquoi une veille réglementaire ?\n\nLe cadre réglementaire QHSE est en constante évolution. Une veille structurée permet d'anticiper les changements, d'adapter les pratiques et d'éviter les sanctions.\n\n## Sources réglementaires clés\n\n### Au Maroc\n- **Code du travail** (loi 65-99)\n- **Loi 12-90** sur les conditions de travail\n- **Loi 28-07** sur la sécurité sanitaire\n- **Loi 13-03** sur les EIE\n- Arrêtés ministériels et notes circulaires\n\n### Internationales\n- Directives européennes\n- Conventions de l'OIT\n- Normes ISO\n- Règlements REACH, CLP (UE)\n\n## Méthodologie de veille\n\n### 1. Identification des textes applicables\nInventorier tous les textes réglementaires pertinents pour l'activité de l'entreprise.\n\n### 2. Collecte et surveillance\nAbonnement aux sources officielles (Bulletin officiel, sites ministériels), utilisation d'outils de veille spécialisés.\n\n### 3. Analyse d'impact\nÉvaluer les conséquences de chaque nouveau texte sur l'organisation.\n\n### 4. Diffusion et mise en œuvre\nCommuniquer les évolutions aux responsables concernés, planifier les actions de mise en conformité.\n\n## Outils\n\n- **Registre réglementaire** : Base de données des textes applicables\n- **Matrice de conformité** : État de conformité par exigence\n- **Logiciels de veille** : Alertes automatiques sur les modifications\n- **Calendrier réglementaire** : Échéances de mise en conformité"},

  {"cat":"management","title":"Culture sécurité : comment la développer en entreprise","excerpt":"La culture sécurité est le facteur clé pour réduire les accidents. Découvrez les leviers pour construire une culture de sécurité forte.","content":"# Culture sécurité : comment la développer en entreprise\n\n## Définition\n\nLa **culture sécurité** est l'ensemble des valeurs, croyances, perceptions et comportements partagés au sein d'une organisation en matière de santé et sécurité au travail.\n\n## Les 4 niveaux de culture sécurité (Parker et al.)\n\n### 1. Culture pathologique\nLa sécurité n'est pas une priorité. Les accidents sont considérés comme inévitables.\n\n### 2. Culture réactive\nLa sécurité devient importante après un accident. Réponse aux incidents mais pas de prévention proactive.\n\n### 3. Culture calculatrice\nSystèmes de gestion de la sécurité en place. La sécurité est gérée par des systèmes et des données.\n\n### 4. Culture proactive\nLa sécurité est une valeur intrinsèque. Les employés s'autogèrent et anticipent les risques.\n\n## Leviers d'action\n\n### Leadership engagé\nLa direction doit montrer l'exemple par des visites terrain, des discussions sécurité et des décisions alignées.\n\n### Participation des employés\nImpliquer les opérateurs dans l'identification des risques et la recherche de solutions.\n\n### Communication transparente\nPartager les incidents, les leçons apprises et les performances sécurité.\n\n### Formation continue\nDépasser la formation réglementaire pour développer les compétences de raisonnement sécurité.\n\n### Reconnaissance\nRécompenser les comportements sûrs, signaler les situations dangereuses sans sanction.\n\n## Indicateurs de culture sécurité\n\n- Taux de signalement des quasi-accidents\n- Nombre de suggestions sécurité\n- Participation aux formations volontaires\n- Résultats des enquêtes de climat sécurité"},

  {"cat":"management","title":"Indicateurs et tableaux de bord QHSE","excerpt":"Les KPI QHSE mesurent les performances et pilote l'amélioration continue. Guide de sélection et de mise en œuvre.","content":"# Indicateurs et tableaux de bord QHSE\n\n## Pourquoi des indicateurs QHSE ?\n\nLes indicateurs permettent de mesurer les performances, de suivre les tendances, d'anticiper les risques et de piloter l'amélioration continue du système QHSE.\n\n## Types d'indicateurs\n\n### Indicateurs de résultat (lagging)\nMesurent les événements passés :\n- Taux de fréquence des accidents (TF) = (Nb accidents x 10⁶) / Heures travaillées\n- Taux de gravité (TG) = (Nb jours perdus x 10³) / Heures travaillées\n- Taux de fréquence des maladies professionnelles\n- Nombre de non-conformités client\n- Tonnage de déchets produits\n\n### Indicateurs de pilotage (leading)\nAnticipent les résultats futurs :\n- Taux de réalisation des actions correctives\n- Pourcentage de formation sécurité réalisée\n- Taux de clôture des observations sécurité\n- Pourcentage d'audits programmés réalisés\n- Taux de participation aux formations\n\n## Construction du tableau de bord\n\n### Sélection des indicateurs\n- Pertinence par rapport aux objectifs QHSE\n- Disponibilité des données\n- Compréhension par tous les acteurs\n- Limité à 8-12 indicateurs maximum\n\n### Fréquence de suivi\n- Quotidien : Indicateurs de sécurité critiques\n- Mensuel : Tableau de bord QHSE global\n- Trimestriel : Revue de direction\n- Annuel : Bilan QHSE et objectifs\n\n## Outils de visualisation\n\n- Tableaux de bord Excel/Power BI\n- Graphiques de tendance et Pareto\n- Cartes de chaleur des risques\n- Dashboards interactifs en ligne"},
]

# ════════════ REGLEMENTATION (need 7 more) ═══════════
articles += [
  {"cat":"reglementation","title":"Code du travail marocain : obligations de l'employeur","excerpt":"Le Code du travail marocain (loi 65-99) définit les droits et obligations en matière de SST. Guide des principales dispositions.","content":"# Code du travail marocain : obligations de l'employeur\n\n## Cadre législatif\n\nLa **loi 65-99** (Code du travail) et la **loi 12-90** (conditions de travail) constituent le socle législatif de la santé et sécurité au travail au Maroc.\n\n## Obligations de l'employeur\n\n### Services de santé au travail (Art. 304-334)\n- Entreprises de 50+ salariés : Service interne de médecine du travail\n- Entreprises de moins de 50 : Médecin du travail conventionné\n- Visite médicale d'embauche, périodique et de reprise\n\n### Comité de sécurité et d'hygiène (Art. 337-347)\n- Entreprises de 50+ salariés : Obligation de créer un CSHT\n- Composition : Employeur, représentants des salariés, médecin du travail\n- Missions : Enquêtes d'accidents, propositions d'amélioration, veille réglementaire\n\n### Déclaration d'accident (Art. 22-25)\n- Déclaration à la CNSS dans les 48h\n- Registre des accidents du travail\n- Enquête pour tout accident grave\n\n### Équipements de protection\n- Fourniture gratuite d'EPI adaptés au risque\n- Vérification et maintenance des installations\n- Signalisation de sécurité\n\n## Infractions et sanctions\n\nLes infractions aux dispositions SST sont punies d'amendes de 300 à 5 000 DH et, en cas de récidive, de peines d'emprisonnement de 1 à 5 jours."},

  {"cat":"reglementation","title":"Risques professionnels : classification et prévention","excerpt":"Les risques professionnels sont classifiés en plusieurs catégories. Cadre légal et mesures de prévention selon le type de risque.","content":"# Risques professionnels : classification et prévention\n\n## Classification des risques\n\n### Risques physiques\nBruit, vibrations, rayonnements ionisants et non ionisants, températures extrêmes, éclairage insuffisant.\n\n### Risques chimiques\nSubstances dangereuses (CMR, toxiques, irritantes), poussières, fumées, vapeurs, gaz.\n\n### Risques biologiques\nBactéries, virus, champignons, parasites (secteur santé, agriculture, laboratoires).\n\n### Risques ergonomiques\nManutention manuelle, postures contraignantes, mouvements répétitifs, travail sur écran.\n\n### Risques psychosociaux\nStress au travail, harcèlement, burn-out, violence au travail.\n\n### Risques organisationnels\nTravail de nuit, horaires atypiques, travail isolé.\n\n## Cadre réglementaire\n\n### Maroc\n- Loi 65-99 (Code du travail)\n- Arrêtés ministériels spécifiques par risque\n- Normes marocaines (NM)\n\n### International\n- Convention 155 de l'OIT (SST)\n- Directives européennes (89/391, 89/654, 90/269, etc.)\n\n## Principes généraux de prévention (Directive 89/391)\n\n1. Éviter les risques\n2. Évaluer les risques qui ne peuvent être évités\n3. Combattre les risques à la source\n4. Adapter le travail à l'homme\n5. Tenir compte de l'évolution de la technique\n6. Remplacer ce qui est dangereux\n7. Planifier la prévention\n8. Prendre des mesures de protection collective\n9. Donner les instructions appropriées"},

  {"cat":"reglementation","title":"Inspection du travail : rôle et pouvoirs","excerpt":"L'inspection du travail veille au respect de la législation. Découvrez ses pouvoirs d'enquête et de sanction.","content":"# Inspection du travail : rôle et pouvoirs\n\n## Mission\n\nL'**inspection du travail** est chargée de veiller à l'application de la législation du travail, de la sécurité sociale et de la médecine du travail.\n\n## Attributions (Art. 529-556)\n\n### Contrôle de la conformité\n- Vérification du respect du Code du travail\n- Contrôle des conditions de sécurité et d'hygiène\n- Vérification des registres obligatoires\n- Contrôle du travail des mineurs et des femmes\n\n### Pouvoirs d'enquête\n- Accès libre à tout établissement (jour et nuit)\n- Demande de communication de documents\n- Prélèvement d'échantillons\n- Audition des salariés et de l'employeur\n\n### Pouvoirs de sanction\n- Mises en demeure avec délai\n- Procès-verbal d'infraction transmis au tribunal\n- Saisine du tribunal en cas de danger imminent\n- Arrêt temporaire d'activité en cas de risque grave\n\n## Registre d'observations\n\nL'inspecteur consigne ses observations dans un registre tenu par l'employeur. L'employeur doit répondre dans les délais impartis.\n\n## Droits des inspecteurs\n\n- Liberté d'accès aux établissements\n- Indépendance vis-à-vis des employeurs\n- Secret professionnel\n- Protection contre les représailles"},

  {"cat":"reglementation","title":"Sécurité dans le BTP : réglementation et bonnes pratiques","excerpt":"Le secteur du BTP est l'un des plus dangereux. Réglementation spécifique et mesures de prévention pour les chantiers.","content":"# Sécurité dans le BTP : réglementation et bonnes pratiques\n\n## Le BTP : un secteur à risques\n\nLe BTP représente environ **25% des accidents du travail** au Maroc, avec une forte proportion d'accidents graves et mortels. Les principales causes sont les chutes de hauteur, les chutes d'objets, l'électrocution et les accidents de circulation.\n\n## Cadre réglementaire\n\n### Plan Général de Coordination (PGC)\nObligatoire pour les chantiers de plus de 500 homme-jours, il définit les mesures de prévention communes à toutes les entreprises.\n\n### Plan Particulier de Sécurité et de Protection de la Santé (PPSPS)\nChaque entreprise intervenant sur le chantier doit établir son PPSPS, intégrant les spécificités de ses activités.\n\n### Coordination SPS\nLe coordinateur SPS organise la cohérence des mesures de prévention entre les différentes entreprises.\n\n## Risques spécifiques et prévention\n\n### Chutes de hauteur\n- Garde-corps (lisse 1m, plinthe 15cm, lisse intermédiaire)\n- Echafaudages conformes (norme NM/EN 12810)\n- Harnais de sécurité avec ligne de vie\n- Travaux en hauteur : formation obligatoire\n\n### Risques électriques\n- Consignation des installations (Habilitation électrique)\n- Outils isolés et EPI diélectriques\n- Distance minimale par rapport aux lignes électriques\n\n### Co-activité\n- Planification des interventions\n- Zones de travail délimitées et signalées\n- Communication entre les entreprises\n\n### Manutention\n- Équipements de levage (grues, nacelles) vérifiés\n- Formation des opérateurs (CACES)\n- Aide à la manutention (diables, chariots)"},

  {"cat":"reglementation","title":"Formation obligatoire en santé et sécurité au travail","excerpt":"La formation SST est une obligation légale. Découvrez les formations requises par type de poste et de risque.","content":"# Formation obligatoire en santé et sécurité au travail\n\n## Cadre légal\n\nLe Code du travail (art. 12) et la loi 12-90 imposent à l'employeur l'obligation de former ses travailleurs aux risques liés à leur poste de travail.\n\n## Formations obligatoires\n\n### Formation à l'embauche\nTout nouveau salarié doit recevoir une formation sur les risques spécifiques de son poste, les mesures de prévention et les consignes de sécurité.\n\n### Formation continue SST\nRenouvellement périodique de la formation selon les risques :\n- **Annuelle** : Travailleurs en hauteur, conducteurs d'engins\n- **Biennale** : Secouristes du travail, manutentionnaires\n- **Triennale** : Autres travailleurs exposés\n\n### Formations spécifiques\n\n#### Habilitation électrique (Norme NM/FC 18-550)\nB0, B1, B2, BR, BC, BE pour les travaux sous tension.\n\n#### CACES (Certificat d'Aptitude à la Conduite En Sécurité)\nR489 (chariots), R390 (nacelles), R386 (grues mobiles).\n\n#### Sauveteur-Secouriste du Travail (SST)\nFormation de 10 à 14 heures pour les gestes de premiers secours en entreprise.\n\n#### Travail en hauteur\nFormation pour l'utilisation des EPI antichute et des échafaudages.\n\n## Responsabilité de l'employeur\n\nL'absence de formation peut être retenue comme faute inexcusable de l'employeur en cas d'accident du travail. Les poursuites pénales sont également possibles."},

  {"cat":"reglementation","title":"Réglementation des produits chimiques : étiquetage CLP et FDS","excerpt":"La réglementation CLP harmonise l'étiquetage des produits chimiques. Comprendre les pictogrammes et les FDS.","content":"# Réglementation des produits chimiques : étiquetage CLP et FDS\n\n## Le règlement CLP\n\nLe **CLP** (Classification, Labelling and Packaging) harmonise la classification et l'étiquetage des substances et mélanges chimiques selon le **SGH** (Système Général Harmonisé de l'ONU).\n\n## Les 9 pictogrammes de danger\n\n1. **Flamme** : Inflammable\n2. **Flamme sur cercle** : Inflammable, comburant\n3. **Explosion** : Explosif\n4. **Bouteille de gaz** : Gaz sous pression\n5. **Corrosion** : Corrosif, irritant\n6. **Crâne et os croisés** : Toxique aiguë, mortel\n7. **Silhouette humaine** : Nocif, irritant\n8. **Arbre et poisson mort** : Dangereux pour l'environnement\n9. **Exclamation** : Danger divers\n\n## Mentions de danger (H-phrases)\n\nExemples :\n- **H225** : Liquide et vapeurs très inflammables\n- **H301** : Toxique en cas d'ingestion\n- **H314** : Provoque des brûlures graves\n- **H317** : Peut provoquer une allergie cutanée\n- **H410** : Très toxique pour les organismes aquatiques\n\n## Fiche de Données de Sécurité (FDS)\n\nDocument en 16 sections obligatoires :\n1. Identification du produit\n2. Composition/informations sur les composants\n3. Identification des dangers\n4. Premiers secours\n5. Mesures de lutte contre l'incendie\n6. Mesures en cas de dispersion accidentelle\n7. Manipulation et stockage\n8. Contrôle de l'exposition/protection individuelle\n9. Propriétés physiques et chimiques\n10. Stabilité et réactivité\n11. Informations toxicologiques\n12. Informations écologiques\n13. Considérations relatives à l'élimination\n14. Informations relatives au transport\n15. Informations réglementaires\n16. Autres informations"},

  {"cat":"reglementation","title":"Responsabilité pénale et civile en matière de SST","excerpt":"En cas d'accident du travail, la responsabilité de l'employeur peut être engagée. Cadre juridique et jurisprudence.","content":"# Responsabilité pénale et civile en matière de SST\n\n## Types de responsabilité\n\n### Responsabilité pénale\nSanctions prononcées par le tribunal pénal à l'encontre de l'auteur de l'infraction (amendes, emprisonnement).\n\n### Responsabilité civile\nObligation de réparer le préjudice subi par la victime (indemnisation).\n\n### Responsabilité administrative\nSanctions infligées par l'autorité administrative (mise en demeure, fermeture, suspension d'activité).\n\n## Faute inexcusable de l'employeur\n\nL'employeur a commis une **faute inexcusable** lorsqu'il avait conscience du danger auquel était exposé le salarié et qu'il n'a pas pris les mesures nécessaires pour l'en préserver.\n\n### Conséquences\n- Majoration de la rente d'incapacité (jusqu'à 100%)\n- Indemnisation supplémentaire pour préjudice moral et esthétique\n- Indemnisation pour perte de chance professionnelle\n\n## Infractions courantes\n\n- Absence de formation à la sécurité\n- Non-fourniture d'EPI\n- Non-respect des normes techniques\n- Défaut de mise en conformité après mise en demeure\n- Non-déclaration d'accident du travail\n\n## Prévention de la responsabilité\n\n### Mesures protectrices\n- Évaluation documentée des risques\n- Formation et information du personnel\n- Mise à jour du document unique\n- Réalisation des audits de conformité\n- Consignation de toutes les actions de prévention\n- Assurances responsabilité civile professionnelle"},

  # Extra management article to reach 10
  {"cat":"management","title":"Gestion des compétences QHSE : plan de formation","excerpt":"Un plan de formation QHSE structuré est essentiel pour développer les compétences. Méthodologie de conception et de suivi.","content":"# Gestion des compétences QHSE : plan de formation\n\n## Pourquoi un plan de formation QHSE ?\n\nLa compétence du personnel est un facteur déterminant de la performance QHSE. Un plan de formation structuré permet de combler les lacunes, de maintenir les compétences et de préparer les évolutions.\n\n## Méthodologie en 5 étapes\n\n### 1. Identification des besoins\n- Analyse des écarts de compétences\n- Résultats des audits et inspections\n- Accidents et quasi-accidents\n- Évolutions réglementaires et technologiques\n- Entretiens annuels d'évaluation\n\n### 2. Planification\n- Priorisation par risque et par urgence\n- Définition des objectifs pédagogiques\n- Choix des modalités (présentiel, e-learning, TP)\n- Budget et ressources nécessaires\n\n### 3. Conception des formations\n- Contenus adaptés au public cible\n- Cas pratiques issus de l'entreprise\n- Évaluations de début et fin de formation\n- Supports pédagogiques variés\n\n### 4. Mise en œuvre\n- Planification logistique\n- Communication auprès des participants\n- Respect des obligations réglementaires\n- Accueil et suivi des stagiaires\n\n### 5. Évaluation de l'efficacité\n- Évaluation à chaud (satisfaction)\n- Évaluation à froid (acquisition des compétences)\n- Évaluation des comportements en situation de travail\n- Impact sur les indicateurs QHSE\n\n## Matrice des compétences\n\nOutil de suivi permettant de visualiser le niveau de compétence de chaque collaborateur par rapport aux exigences de son poste, et de planifier les formations nécessaires."},
]

# ═══════════ EXECUTE ═══════════
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Get categories
cursor.execute("SELECT id, slug FROM Category ORDER BY \"order\"")
cats = {row[1]: row[0] for row in cursor.fetchall()}

created = 0
skipped = 0
errors = 0

for i, a in enumerate(articles):
    cat_id = cats.get(a['cat'])
    if not cat_id:
        print(f"SKIP: no category {a['cat']}")
        skipped += 1
        continue

    slug = slugify(a['title'])
    
    cursor.execute("SELECT id FROM Article WHERE slug = ?", (slug,))
    if cursor.fetchone():
        skipped += 1
        continue

    cover = img(a['cat'], i % 5)
    now = datetime.utcnow().isoformat()
    
    try:
        cursor.execute("""
            INSERT INTO Article (id, title, slug, excerpt, content, coverImage, published, featured, authorName, categoryId, viewCount, createdAt, updatedAt)
            VALUES (?, ?, ?, ?, ?, ?, 1, 0, 'IICP', ?, 0, ?, ?)
        """, (
            f"art_{slug[:30]}_{i}", a['title'], slug, a['excerpt'], a['content'],
            cover, cat_id, now, now
        ))
        created += 1
        print(f"✓ [{a['cat']}] {a['title'][:60]}...")
    except Exception as e:
        if 'UNIQUE' in str(e):
            skipped += 1
        else:
            errors += 1
            print(f"✗ Error: {a['title'][:40]}... - {e}")

conn.commit()

print(f"\n{'='*50}")
print(f"Created: {created}, Skipped: {skipped}, Errors: {errors}")
print(f"\nFinal counts:")

cursor.execute("""
    SELECT c.name, COUNT(a.id) 
    FROM Category c 
    LEFT JOIN Article a ON a.categoryId = c.id 
    GROUP BY c.id 
    ORDER BY c."order"
""")
for row in cursor.fetchall():
    print(f"  {row[0]}: {row[1]} articles")

conn.close()