import { db } from '../src/lib/db';

async function main() {
  console.log('Adding certified trainings...');

  const formations = [
    {
      title: "Sauveteur Secouriste du Travail (SST)",
      slug: "sauveteur-secouriste-travail-sst",
      shortDescription: "Formation obligatoire permettant d'assurer les premiers secours en entreprise. Délivrance du certificat de SST conforme aux recommandations INRS.",
      fullDescription: "La formation de Sauveteur Secouriste du Travail (SST) est une obligation réglementaire pour toute entreprise (Code du travail, article R4224-14). Le SST est capable de porter secours à une victime en attendant l'arrivée des secours professionnels. Cette formation est dispensée selon les recommandations de l'INRS et de la Caisse d'Assurance Retraite et de Santé au Travail (CARSAT). Le certificat SST est valable 24 mois et nécessite un recyclage périodique.",
      level: "certifiant",
      duration: "2 jours (14 heures)",
      durationHours: "14h",
      prerequisites: "Aucun prérequis. Être salarié d'une entreprise.",
      objectives: JSON.stringify(["Maîtriser la conduite à tenir en cas d'accident du travail", "Savoir alerter les secours professionnels", "Pratiquer les gestes de premiers secours (PAS, PLS, compression, etc.)", "Compléter le Document Unique d'Évaluation des Risques (DUERP)"]),
      program: JSON.stringify(["Le rôle du SST dans l'entreprise et le cadre légal", "La protection et l'alerte aux secours", "La conduite à tenir face à une situation d'accident", "L'examen d'une victime : saignement, brûlure, chute, malaise, inconscience", "Les gestes de premiers secours pratiques (ateliers)", "La mise en position latérale de sécurité (PLS)", "L'utilisation du défibrillateur automatisé externe (DAE)", "Examen final et délivrance du certificat"]),
      priceIndividual: "250 €",
      priceGroup: "220 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: true,
      order: 10,
    },
    {
      title: "Habilitation Électrique B0 / B2 / BR / BC",
      slug: "habilitation-electrique-b0-b2-br-bc",
      shortDescription: "Formation d'habilitation électrique conforme à la NF C 18-510 pour les niveaux B0, B2, BR et BC. Indispensable pour tout travail à proximité ou sur des installations électriques.",
      fullDescription: "L'habilitation électrique est une obligation réglementaire (Code du travail, article R4544-1 à R4544-11) pour tout personnel amené à intervenir sur ou à proximité d'installations électriques. Cette formation respecte la norme NF C 18-510 et les recommandations de la CNAMTS/INRS. Elle permet d'obtenir le titre d'habilitation délivré par l'employeur, attestant de la qualification du salarié. Différents niveaux d'habilitation sont proposés en fonction des tâches à réaliser.",
      level: "certifiant",
      duration: "1 à 3 jours selon le niveau",
      durationHours: "7h à 21h",
      prerequisites: "Connaissances de base en électricité pour les niveaux B2 et supérieurs.",
      objectives: JSON.stringify(["Connaître les risques électriques et leurs conséquences", "Maîtriser les règles de sécurité et les procédures d'intervention", "Savoir utiliser les équipements de protection individuelle (EPI) électriques", "Effectuer les vérifications et consignations nécessaires", "Obtenir le titre d'habilitation correspondant au niveau visé"]),
      program: JSON.stringify(["Rappels sur l'électricité et les effets du courant sur le corps", "Analyse des risques électriques et classification des interventions", "Les limites d'approche et de voisinage", "Les équipements de protection collective et individuelle", "Procédures de consignation et de déconsignation", "Travaux hors tension et travaux au voisinage", "Travaux sous tension (niveaux B2V, B2T, BR)", "Exercices pratiques en situation réelle ou simulée", "Évaluation théorique et pratique", "Délivrance de l'attestation"]),
      priceIndividual: "350 €",
      priceGroup: "300 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: true,
      order: 11,
    },
    {
      title: "Travail en Hauteur - CACES R489",
      slug: "travail-en-hauteur-caces-r489",
      shortDescription: "Formation au travail en hauteur conforme au CACES R489 et aux recommandations INRS. Utilisation des EPI antichute, accès par échelle et nacelle élévatrice.",
      fullDescription: "Le travail en hauteur est l'une des causes principales d'accidents du travail mortels en France (plus de 50 décès par an selon la Cnam). La formation CACES R489 « Établissement des opérateurs de plates-formes élévatrices mobiles de personnes (PEMP) » est devenue obligatoire depuis le 1er janvier 2024. Cette formation couvre également les risques liés à l'utilisation des EPI antichute, aux travaux sur échelle et sur toiture, conformément au décret 2004-924 et aux recommandations INRS ED 6125 et ED 6110.",
      level: "certifiant",
      duration: "2 à 3 jours",
      durationHours: "14h à 21h",
      prerequisites: "Avoir plus de 18 ans. APT médicale valide. Permis B pour les catégories 1B et 3B (nacelles avec déplacement).",
      objectives: JSON.stringify(["Identifier les risques liés au travail en hauteur", "Savoir utiliser les EPI antichute (harnais, longe, absorbeur de choc)", "Conduire une nacelle élévatrice en toute sécurité (CACES R489)", "Appliquer les procédures de secours en cas d'incident", "Maîtriser les vérifications avant mise en service"]),
      program: JSON.stringify(["Réglementation et statistiques des accidents", "Analyse des risques du travail en hauteur", "Les EPI antichute : choix, vérification, entretien et utilisation", "Travaux sur échelles et escabeaux", "CACES R489 Catégorie 1A : PEMP à positionnement inaccessible", "CACES R489 Catégorie 1B : PEMP à déplacement", "CACES R489 Catégorie 3A/3B : PEMP tout-terrain", "Exercices pratiques de conduite et de sauvetage", "Évaluation pratique et théorique"]),
      priceIndividual: "450 €",
      priceGroup: "390 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: true,
      order: 12,
    },
    {
      title: "Intervention en Espaces Confinés",
      slug: "intervention-espaces-confines",
      shortDescription: "Formation à la prévention des risques en espaces confinés. Gaz, manque d'oxygène, ventilation et procédures de sauvetage selon les recommandations INRS.",
      fullDescription: "Les interventions en espaces confinés (cuves, silos, regards, fosses, caves, réservoirs) représentent un risque majeur avec plus de 100 accidents graves par an en France. Cette formation est conforme aux recommandations INRS ED 6120 et à la circulaire DRT n°96-11 du 10 mai 1996. Elle aborde les risques d'asphyxie, d'intoxication par gaz, d'explosion et d'engloutissement, et forme les intervenants aux procédures de travail sécurisées et au sauvetage.",
      level: "certifiant",
      duration: "2 jours",
      durationHours: "14h",
      prerequisites: "Avoir plus de 18 ans. APT médicale valide. Formation SST recommandée.",
      objectives: JSON.stringify(["Identifier les espaces confinés et leurs risques spécifiques", "Maîtriser les procédures d'entrée et de sortie", "Utiliser les détecteurs de gaz et les équipements de protection respiratoire", "Connaître les procédures de sauvetage et d'évacuation d'urgence", "Savoir organiser la surveillance et le secours extérieur"]),
      program: JSON.stringify(["Définition et réglementation des espaces confinés", "Les risques : asphyxie, intoxication, explosion, engloutissement", "Les gaz dangereux : CO, H2S, CH4, O2 déficitaire", "Utilisation des détecteurs de gaz multi-gaz", "Équipements de protection : EPI, EPR, harnais de sauvetage", "Procédures de ventilation et d'assainissement", "Organisation du travail : permis de travail, consignation", "Procédures de sauvetage avec et sans accès", "Exercices pratiques en espace confiné simulé"]),
      priceIndividual: "400 €",
      priceGroup: "350 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 13,
    },
    {
      title: "Équipier de Première Intervention - Incendie",
      slug: "equipier-premiere-intervention-incendie",
      shortDescription: "Formation à la lutte contre l'incendie en entreprise. Utilisation des extincteurs, RIA et évacuation. Conforme à l'article R4227-39 du Code du travail.",
      fullDescription: "La formation d'équipier de première intervention incendie est une obligation pour toute entreprise employant plus de 50 salariés (article R4227-39 du Code du travail). Elle permet de former du personnel capable de mettre en œuvre les premiers moyens de lutte contre un début d'incendie et de déclencher l'alarme. Cette formation respecte les recommandations de la CNAMTS, l'INRS (ED 6105) et les réglementations ERP/IGH. Elle est complémentaire de l'exercice d'évacuation annuel obligatoire.",
      level: "certifiant",
      duration: "1 jour",
      durationHours: "7h",
      prerequisites: "Aucun prérequis.",
      objectives: JSON.stringify(["Connaître le triangle du feu et les classes de feux", "Utiliser correctement les extincteurs appropriés (eau, poudre, CO2)", "Maîtriser l'utilisation du Robinet d'Incendie Armé (RIA)", "Savoir alerter et déclencher l'évacuation", "Connaître les consignes de sécurité incendie de l'établissement"]),
      program: JSON.stringify(["La combustion : le triangle et le tétraèdre du feu", "Les classes de feux et les extincteurs adaptés", "Les installations fixes : RIA, colonne sèche, sprinklage", "Les consignes de sécurité et les plans d'évacuation", "Exercice pratique d'extinction avec extincteurs réels", "Exercice pratique avec le RIA", "Simulation de déclenchement d'alarme et d'évacuation", "Bilan et évaluation des acquis"]),
      priceIndividual: "180 €",
      priceGroup: "150 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 14,
    },
    {
      title: "SSIAP 1 - Service de Sécurité Incendie et d'Assistance à Personnes",
      slug: "ssiap-1-securite-incendie",
      shortDescription: "Formation certifiante SSIAP niveau 1 pour les agents de sécurité incendie. Conforme à l'arrêté du 2 mai 2005 modifié, indispensable pour les ERP et IGH.",
      fullDescription: "Le SSIAP 1 est le premier niveau de certification pour les personnels chargés de la sécurité incendie dans les Établissements Recevant du Public (ERP) et les Immeubles de Grande Hauteur (IGH). Cette formation est obligatoire selon l'arrêté du 2 mai 2005 modifié et le Code de la construction et de l'habitation. L'agent SSIAP 1 assure la prévention, l'application des consignes de sécurité, la surveillance des installations techniques et participe aux secours. La certification est délivrée par le CNPP ou un organisme agréé.",
      level: "certifiant",
      duration: "10 jours (70 heures)",
      durationHours: "70h",
      prerequisites: "Avoir plus de 18 ans. Casier judiciaire vierge. APT médicale. Niveau scolaire minimum collège.",
      objectives: JSON.stringify(["Connaître la réglementation applicable aux ERP et IGH", "Assurer la surveillance des installations techniques de sécurité", "Appliquer les consignes de sécurité incendie", "Utiliser les moyens d'extinction et d'alarme", "Évacuer le public en cas de sinistre", "Accueillir et guider les sapeurs-pompiers"]),
      program: JSON.stringify(["Cadre réglementaire : ERP, IGH, Code de la construction", "Les installations techniques : détection, extinction, désenfumage", "Les différentes catégories d'ERP et leurs spécificités", "Les risques liés aux activités et aux publics accueillis", "Les moyens d'extinction : extincteurs, RIA, colonnes", "Les systèmes de détection incendie et d'alarme", "L'évacuation du public : consignes, exercices, difficultés", "Accueil des secours et information des sapeurs-pompiers", "Visite et étude d'un ERP", "Examen final théorique et pratique (Jury SSIAP)"]),
      priceIndividual: "1 500 €",
      priceGroup: "1 200 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 15,
    },
    {
      title: "CACES R485 - Conduite de Chariots Automoteurs",
      slug: "caces-r485-chariots-automoteurs",
      shortDescription: "Formation CACES R485 pour la conduite de chariots élévateurs en sécurité. Catégories 1A, 1B, 3A, 3B selon le type d'engin utilisé.",
      fullDescription: "Le CACES R485 « Conduite de chariots automoteurs de manutention à conducteur porté » est devenu quasi obligatoire dans le secteur de la logistique et de l'industrie. Bien que non imposé par le Code du travail, il est exigé par la plupart des entreprises et donne lieux à des réductions de cotisations AT/MP. La formation respecte les recommandations INRS ED 6100 et le décret 98-1084. Elle couvre les catégories 1A (transpalettes à conducteur porté), 1B (chariots à mât rétractable), 3A (chariots élévateurs en porte-à-faux de capacité ≤ 6000 kg) et 3B (capacité > 6000 kg).",
      level: "certifiant",
      duration: "2 à 5 jours selon catégorie",
      durationHours: "14h à 35h",
      prerequisites: "Avoir plus de 18 ans. Permis B valide pour les chariots automoteurs. APT médicale.",
      objectives: JSON.stringify(["Conduire un chariot en toute sécurité", "Connaître les risques liés à la manutention", "Effectuer les vérifications avant et après utilisation", "Maîtriser les manœuvres de chargement et déchargement", "Obtenir le CACES R485 de la catégorie souhaitée"]),
      program: JSON.stringify(["Réglementation et responsabilités du cariste", "Les différents types de chariots et leurs caractéristiques", "Les risques : renversement, écrasement, chute de charge", "La stabilité du chariot et de la charge", "Les vérifications journalières et périodiques", "La conduite : démarrage, marche, virage, freinage", "Le levage, le gerbage et le dégerbage de charges", "La circulation en entreprise et les règles de priorité", "Exercices pratiques sur chaque catégorie", "Examen théorique et pratique devant un jury CACES"]),
      priceIndividual: "550 €",
      priceGroup: "480 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 16,
    },
    {
      title: "CACES R482 - Grues et Appareils de Levage",
      slug: "caces-r482-grues-appareils-levage",
      shortDescription: "Formation CACES R482 pour la conduite de grues à tour et grues mobiles. Conforme aux recommandations INRS et à l'arrêté du 2 décembre 1998.",
      fullDescription: "La formation CACES R482 est indispensable pour conduire des grues à tour et des grues sur camion. L'arrêté du 2 décembre 1998 rend obligatoire la formation des conducteurs d'équipements de levage. Cette formation couvre la conduite en sécurité, la vérification des équipements, l'interprétation des diagrammes de charge et la gestion des risques liés au levage de charges en hauteur. Le CACES R482 est requis sur la plupart des chantiers de BTP et dans l'industrie.",
      level: "certifiant",
      duration: "5 à 10 jours",
      durationHours: "35h à 70h",
      prerequisites: "Avoir plus de 18 ans. Permis B valide. APT médicale. Expérience en BTP recommandée.",
      objectives: JSON.stringify(["Conduire une grue en toute sécurité sur chantier", "Lire et interpréter les diagrammes de charge", "Effectuer les vérifications journalières et les opérations de maintenance", "Coordonner les opérations de levage avec les équipes au sol", "Obtenir le CACES R482"]),
      program: JSON.stringify(["Réglementation du levage et responsabilités", "Types de grues : à tour, sur camion, mobile", "Les composants de la grue et leurs fonctions", "Lecture et interprétation des diagrammes de charge", "Les effets du vent et des conditions météorologiques", "Les EPI et les équipements de sécurité", "Manœuvres de levage, balancement et dépôt", "Communication avec le signaleur et les équipes au sol", "Vérifications journalières et entretien", "Exercices pratiques et examen CACES"]),
      priceIndividual: "2 200 €",
      priceGroup: "1 900 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 17,
    },
    {
      title: "Risques Chimiques - Évaluation et Prévention",
      slug: "risques-chimiques-evaluation-prevention",
      shortDescription: "Formation à l'évaluation et à la prévention des risques chimiques. Étiquetage CLP, FDS, EPI et procédures de travail selon le règlement REACH.",
      fullDescription: "Les risques chimiques sont omniprésents en milieu professionnel et représentent la 3ème cause de maladie professionnelle en France. Cette formation aborde l'évaluation des risques chimiques selon la méthodologie INRS, la lecture et l'interprétation des Fiches de Données de Sécurité (FDS) au format SDS-GHS/CLP, le classement des dangers selon le SGH, et les mesures de prévention collective et individuelle. Elle est conforme au règlement CLP (CE n°1272/2008) et REACH (CE n°1907/2006), ainsi qu'aux recommandations INRS ED 6100 et ED 972.",
      level: "certifiant",
      duration: "2 jours",
      durationHours: "14h",
      prerequisites: "Connaissances de base en QHSE recommandées.",
      objectives: JSON.stringify(["Lire et interpréter une Fiche de Données de Sécurité (FDS)", "Comprendre l'étiquetage CLP/GHS et les pictogrammes de danger", "Évaluer les risques chimiques selon la méthodologie INRS", "Mettre en place les mesures de prévention collective et individuelle", "Rédiger une fiche de poste à risque chimique", "Gérer le stockage et l'élimination des produits chimiques"]),
      program: JSON.stringify(["Le cadre réglementaire : CLP, REACH, Code du travail", "Les dangers des produits chimiques : toxicité, inflammabilité, corrosivité", "Le SGH et les 9 pictogrammes de danger", "L'étiquetage CLP et les mentions de danger", "La FDS : structure, lecture et utilisation", "Méthodologie d'évaluation des risques chimiques INRS", "Les VLEP et VME : valeurs limites d'exposition", "Mesures de prévention collective (ventilation, captage, substitution)", "Les EPI spécifiques : gants, lunettes, masques, tenues", "Cas pratiques et ateliers d'évaluation"]),
      priceIndividual: "350 €",
      priceGroup: "300 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 18,
    },
    {
      title: "Manutention Manuelle et Port de Charge - PRAP",
      slug: "manutention-manuelle-port-charge-prap",
      shortDescription: "Formation PRAP (Prévention des Risques liés à l'Activité Physique) pour la manutention manuelle. Réduction des TMS et gestes sécuritaires au poste de travail.",
      fullDescription: "Les troubles musculosquelettiques (TMS) représentent la première cause de maladie professionnelle en France avec plus de 87 % des maladies professionnelles reconnues. La formation PRAP, recommandée par l'INRS (ED 6100), vise à prévenir les risques liés à la manutention manuelle et à l'activité physique au travail. Elle est conforme au décret 92-958 du 3 septembre 1992 qui fixe les limites de port de charge. Cette formation apprend aux salariés les principes de base du dosage, les gestes sécuritaires et les bonnes postures pour préserver leur santé.",
      level: "certifiant",
      duration: "1 à 2 jours",
      durationHours: "7h à 14h",
      prerequisites: "Aucun prérequis. APT médicale recommandée.",
      objectives: JSON.stringify(["Connaître le fonctionnement du rachis et les mécanismes des TMS", "Appliquer les principes de sécurité en manutention manuelle", "Évaluer le poids et les conditions de port de charge", "Maîtriser les gestes et postures de sécurité", "Utiliser les aides à la manutention adaptées"]),
      program: JSON.stringify(["Anatomie du dos : le rachis, les disques, les muscles", "Les TMS : statistiques, facteurs de risque, conséquences", "Le décret 92-958 et les limites de port de charge", "Les principes de base : dos droit, charge près du corps", "Les gestes techniques : soulever, porter, déposer, pousser, tirer", "Les aides mécaniques : diable, transpalette, ventouse", "L'aménagement ergonomique du poste de travail", "Les échauffements et étirements préventifs", "Exercices pratiques de manutention en situation réelle"]),
      priceIndividual: "180 €",
      priceGroup: "150 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 19,
    },
    {
      title: "AMOX - Agent de Maîtrise des Risques",
      slug: "amox-agent-maitrise-risques",
      shortDescription: "Formation AMOX pour les agents chargés de la mise en œuvre des règles d'hygiène et de sécurité. Conforme à l'arrêté du 25 février 2016 pour les ERP de type L.",
      fullDescription: "L'Agent de Maîtrise des Risques (AMOX) est un agent de sécurité incendie confirmé qui assure la permanence de la sécurité dans les Établissements Recevant du Public (ERP). La formation AMOX est obligatoire dans les ERP de type L (salles d'auditions, de réunions, de spectacles ou à usages multiples) où la présence d'un AMOX est exigée par le Code de la construction et de l'habitation. Cette formation est conforme à l'arrêté du 25 février 2016 et complète les compétences du SSIAP avec des connaissances approfondies en prévention et gestion des risques.",
      level: "certifiant",
      duration: "5 jours (35 heures)",
      durationHours: "35h",
      prerequisites: "Certificat SSIAP 1 valide. Expérience en sécurité incendie.",
      objectives: JSON.stringify(["Assurer la permanence de la sécurité incendie dans un ERP", "Effectuer les rondes de surveillance et les vérifications techniques", "Gérer les consignes de sécurité et les permis de travail", "Accueillir les secours et leur transmettre les informations", "Rédiger les rapports de sécurité et les registres de sécurité"]),
      program: JSON.stringify(["Rappels réglementaires ERP et IGH", "Les installations techniques : détection, extinction, désenfumage, alarme", "La gestion du service de sécurité : planning, astreintes, consignes", "Les rondes de sécurité : points de contrôle, fréquence, registre", "Les permis de travail et les consignes particulières", "La gestion des travaux en ERP par entreprises extérieures", "L'accueil et la prise en charge des sapeurs-pompiers", "La rédaction des rapports de sécurité", "Études de cas et exercices de simulation", "Examen final théorique et pratique"]),
      priceIndividual: "950 €",
      priceGroup: "800 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 20,
    },
    {
      title: "CSE / CSSCT - Formation des Élus au Risque Professionnel",
      slug: "cse-cssct-formation-elus-risque-professionnel",
      shortDescription: "Formation obligatoire des membres du CSE/CSSCT à la santé et sécurité au travail. Conforme à l'article L2315-18 du Code du travail.",
      fullDescription: "La formation des membres du Comité Social et Économique (CSE) et de la Commission Santé, Sécurité et Conditions de Travail (CSSCT) est une obligation légale (Code du travail, article L2315-18). Cette formation, financée par l'employeur, permet aux élus d'acquérir les compétences nécessaires pour exercer leur rôle en matière de santé et sécurité. Elle est délivrée par un organisme certificateur et respecte le référentiel du Ministère du Travail. La formation doit être d'au moins 5 jours pour les entreprises de plus de 300 salariés et 3 jours en dessous de ce seuil.",
      level: "certifiant",
      duration: "3 à 5 jours",
      durationHours: "21h à 35h",
      prerequisites: "Être membre élu du CSE ou de la CSSCT.",
      objectives: JSON.stringify(["Connaître le rôle et les attributions du CSE en matière de SSCT", "Maîtriser les principes généraux de prévention (article L4121-1)", "Savoir analyser les risques professionnels et le DUERP", "Comprendre les enquêtes après accident du travail", "Exercer le droit d'alerte en cas de danger grave et imminent"]),
      program: JSON.stringify(["Le cadre légal : Code du travail, CSE, CSSCT, inspecteur du travail", "Le rôle du CSE en matière de santé, sécurité et conditions de travail", "Les principes généraux de prévention (9 principes de l'article L4121-1)", "Le Document Unique d'Évaluation des Risques Professionnels (DUERP)", "Les risques majeurs : chutes, manutention, chimique, bruit, vibrations", "L'enquête après accident du travail et maladie professionnelle", "Le droit d'alerte et le droit de retrait", "L'analyse des conditions de travail et la pénibilité", "Visite d'entreprise et analyse de situations réelles", "Mise en situation et évaluation des acquis"]),
      priceIndividual: "600 €",
      priceGroup: "500 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 21,
    },
    {
      title: "Permis de Feu et Travaux à Chaud",
      slug: "permis-feu-travaux-a-chaud",
      shortDescription: "Formation au permis de feu pour les travaux à chaud (soudure, meulage, découpe). Prévention des risques d'incendie sur les sites industriels et chantiers.",
      fullDescription: "Les travaux à chaud (soudure, découpe, meulage, brasure) sont la cause de nombreux incendies en milieu professionnel. La mise en place d'un permis de feu est une obligation réglementaire pour les ERP de type U (établissements de soins), I (établissements de type institut) et J (structures d'accueil pour personnes âgées). Cette formation forme les opérateurs et les responsables sécurité à la rédaction, à la vérification et au suivi du permis de feu, ainsi qu'aux mesures de prévention et de surveillance pendant et après les travaux à chaud.",
      level: "certifiant",
      duration: "1 jour",
      durationHours: "7h",
      prerequisites: "Aucun prérequis. Formation incendie de base recommandée.",
      objectives: JSON.stringify(["Rédiger et vérifier un permis de feu", "Connaître les mesures de prévention pendant les travaux à chaud", "Assurer la surveillance pendant et après les travaux", "Maîtriser les équipements de protection et d'extinction", "Connaître les procédures d'urgence en cas de déclenchement d'incendie"]),
      program: JSON.stringify(["Le cadre réglementaire et juridique du permis de feu", "Les travaux à chaud : définition, risques et statistiques", "La procédure de permis de feu : rédaction, vérification, suivi", "Les mesures de prévention avant, pendant et après les travaux", "La surveillance post-travaux (minimum 2 heures)", "Les équipements de protection individuelle et collective", "Les extincteurs et moyens de première intervention", "Cas pratiques et exercices de rédaction de permis de feu", "Simulation d'incendie et utilisation des extincteurs"]),
      priceIndividual: "200 €",
      priceGroup: "170 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 22,
    },
    {
      title: "Conduite en Sécurité - Permis B et Éco-conduite",
      slug: "conduite-securite-permis-eco-conduite",
      shortDescription: "Formation à la conduite en sécurité et à l'éco-conduite pour les conducteurs d'entreprise. Réduction de la consommation de carburant et prévention des accidents.",
      fullDescription: "La conduite en sécurité et l'éco-conduite sont des enjeux majeurs pour les entreprises : les accidents de la route représentent la 1ère cause de mortalité au travail, et la consommation de carburant est un poste de dépenses significatif. Cette formation, conforme au Code de la route et aux recommandations de l'INRS (ED 6101), vise à réduire les risques d'accidents et la consommation de carburant. Elle est particulièrement adaptée aux flottes d'entreprise, aux livreurs et aux commerciaux itinérants. L'éco-conduite permet de réduire la consommation de 5 à 15 % selon l'ADEME.",
      level: "certifiant",
      duration: "1 jour",
      durationHours: "7h",
      prerequisites: "Permis B valide. APT médicale.",
      objectives: JSON.stringify(["Adopter une conduite préventive et défensive", "Réduire sa consommation de carburant de 5 à 15 %", "Connaître les risques routiers liés à l'activité professionnelle", "Maîtriser les distances d'arrêt et les temps de réaction", "Appliquer les principes de l'éco-conduite au quotidien"]),
      program: JSON.stringify(["Bilan de l'accidentalité routière en France et en entreprise", "Les facteurs d'accident : vitesse, fatigue, alcool, téléphone", "La conduite préventive : anticipation, observation, marges de sécurité", "Les distances d'arrêt, de freinage et de sécurité", "L'éco-conduite : principes, techniques et bénéfices", "La gestion de la vitesse et des régimes moteur", "L'entretien du véhicule et le contrôle technique", "Les situations d'urgence : freinage, évitement, perte d'adhérence", "Exercices pratiques de conduite sur circuit"]),
      priceIndividual: "220 €",
      priceGroup: "190 € / personne",
      priceEnterprise: "Sur demande",
      mode: "presentiel",
      type: "certifiante",
      featured: false,
      order: 23,
    },
  ];

  let created = 0;
  for (const f of formations) {
    try {
      await db.formation.create({ data: f });
      console.log(`✅ ${f.title}`);
      created++;
    } catch (e: any) {
      console.log(`⚠️ ${f.title}: ${e.message?.substring(0, 60)}`);
    }
  }

  const total = await db.formation.count();
  const cert = await db.formation.count({ where: { type: 'certifiante' } });
  const dip = await db.formation.count({ where: { type: 'diplomante' } });
  console.log(`\nCréées: ${created} | Certifiantes: ${cert} | Diplômantes: ${dip} | Total: ${total}`);
}

main().catch(e => { console.error(e); process.exit(1); });